### ISSUE TITLE
Domain aliases for flexibility in schema selection.

### ISSUE THREAD

**Issue by develmaycare** [bernardopires/django-tenant-schemas#10]
My particular use-case may be on the edge, but I have a situation where I need the dynamic schema selection to occur on two or more domain names. For example, subdomain1.example.com and subdomain2.example.net could both use the same postgres schema. The solution I implemented was to:
- Add a domain_aliases field to the TenantMixin as a TextField. Aliases would be entered as space separated values.
- Alter the middleware to first check for the domain_url, but then also check for domains_aliases__contains.
- An Http404 is still raised if neither is found.

One _could_ implement the domain_aliases as an external table, but it seems like this simpler approach would work, and saves an additional relationship. I suppose my solution _could_ be reduced to a single database call by using filter() once instead of get() twice, but the result would be less precise.

At any rate, I pushed this change into production these evening and it works great. 

Would anyone like to see the code? Or receive a pull request?

**Comment by tobiasgoecke** [comment]
@bernardopires Is the field domain_aliases not existing in the master branch version?
