### ISSUE TITLE
Tenant schemas and Django Admin

### ISSUE THREAD

**Issue by bimsapi** [bernardopires/django-tenant-schemas#110]
What is the correct way to configure the admin app for use with tenants? If I put django.contrib.admin and its app dependencies in TENANT_APPS, I get errors because it's trying to find tables in 'public'. 

I want to have tenant-specific users/admins use the admin app to manipulate some (not all) of the model data in their own schemas. I don't know Django well enough to intuit what is causing the contrib.admin to apparently ignore the current tenant.

Any help/guidance is appreciated.

**Comment by m-thielen** [comment]
Old and closed issue, but Google took me here...

I found a much simpler solution than running two Django instances: use two admin sites. 
This is how I did it:

In a tenant app's admin.py:

```
tenant_admin_site = admin.AdminSite(name="tenant-admin")

class SomeModelAdmin(admin.ModelAdmin):
    [...]

tenant_admin_site.register(SomeModel, SomeModelAdmin)
[...]
```

Models in the public schema (SHARED_APPS) are registered the usual way.

Then, in your main urls.py:

```
from django.contrib import admin
from yourapp.admin import tenant_admin_site

urlpatterns = [
    url(r'admin/, admin.site.urls),
    url(r'^tenant-admin/', include(tenant_admin_site.urls)),
    [...]
```

After that, you access your public/shared admin under `/admin/` and the tenant specific under `/tenant-admin/`.
One drawback is that you have to access each tenant app's admin under a separate URL. There might be a solution for that, but I do not need it so I did not try.

**Comment by m-thielen** [comment]
Or, even better (I was too curious):

A Django AdminSite subclass that filters the displayed apps to match the current tenant. For this to work, you need a way to determine if the current tenant is public. I do not use the default subdomain-tenant-approach (mine is cookie-based), so you have to make up something here.

The result of this approach is an admin site that displays either public or shared apps, whatever is appropriate, all under a single admin URL.

My TenantModel (called Project) has a class method `current_is_public` that is used by the following code. You'll have to adopt this to your (probably subdomain-based) implementation.
This is the AdminSite subclass that filters apps (file is named 'tenant_admin.py'):

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from django.conf import settings
from .models import Project  # your TenantModel here


class TenantAwareAdminSite(admin.AdminSite):

    def get_app_list(self, request):
        """ override to return only the apps that are appropriate - tenant aware or public """
        # check if current schema is public
        is_public = Project.current_is_public(request)

        app_list = super(TenantAwareAdminSite, self).get_app_list(request)
        tenant_aware_apps = []

        for app in app_list:
            if is_public:
                if app["app_label"] in settings.SHARED_APPS:
                    tenant_aware_apps.append(app)
            else:
                if app["app_label"] in settings.TENANT_APPS:
                    tenant_aware_apps.append(app)

        return tenant_aware_apps


# tenant aware admin site singleton
admin_site = TenantAwareAdminSite(name="admin")
```

In your apps' admin.py, you do not register with the default admin.site, but the tenant-aware site instance like this:

```
from django.contrib import admin

from .models import Project  # any model class
from .tenant_admin import admin_site  # adopt to the file where your TenantAwareAdminSite is


class ProjectAdmin(admin.ModelAdmin):
    [...]

admin_site.register(Project, ProjectAdmin)

```

**Comment by Jromero97** [comment]
@m-thielen How you implement the current_is_public() method to do that?

**Comment by m-thielen** [comment]
This depends on your implementation/use case. 
My tenant model is named  'Project' and has a boolean field that determines if an instance is public or not. The 'current_is_public()' method is passed the request instance, which it uses to determine the current project:

>    
    @classmethod
    def current_is_public(cls, request):
        project = cls.get_current(request)
        return project and project.is_public

**Comment by Jromero97** [comment]
It is very interesting, that code only shows me Tenant apps, but when i'm in my main domain don't show shared apps, also I have an error with the "get_current" method is unresolved, how can I replace that functionality to verifie the schemas? Thanks for your help @m-thielen

**Comment by ricardovm91** [comment]
Even if the the is closed and old, I ran into this issue today and couldn't find a definitive solution on the internet, just pieces that in the end helped. I'll post this here so if anyone ever encounters this problem, can solve it fast.

**Django version**: 2.0.9 running django-tenant-schemas

**The need**
We needed staff users to be able to get into the admin and manage application's settings through it.

**The problem**
Since we have the django.contrib.auth app in TENANT_APPS we handle independent users for every tenant. When I created a staff user and assign its permissions correctly, django would throw this error when adding, changing, or deleting records:

![error](https://user-images.githubusercontent.com/13007080/56252008-6d269600-607b-11e9-920a-70a2e0b04610.png)

**Failed solutions**
I tried following all kinds of workarounds and fixes but either nothing happened or they demanded a lot of refactoring that I can not do.

**Final approach**
In the end I did 2 things:
1. I made a copy of the LogEntry Model (the model that generates the django_admin_log table), made a change, and added it into one of my apps.

```
import json

from django.conf import settings
from django.contrib.admin.utils import quote
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import NoReverseMatch, reverse
from django.utils import timezone
from django.utils.text import get_text_list
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.models import User

ADDITION = 1
CHANGE = 2
DELETION = 3


class AdminLogEntryManager(models.Manager):
    def log_action(self, user_id, content_type_id, object_id, object_repr, action_flag, change_message=''):
        if isinstance(change_message, list):
            change_message = json.dumps(change_message)
        return self.model.objects.create(
            user_id=user_id,
            content_type_id=content_type_id,
            object_id=str(object_id),
            object_repr=object_repr[:200],
            action_flag=action_flag,
            change_message=change_message,
        )


class AdminLogEntry(models.Model):
    action_time = models.DateTimeField(
        _('action time'),
        default=timezone.now,
        editable=False,
    )
    user = models.ForeignKey(
        User,
        models.CASCADE,
        verbose_name=_('user'),
    )
    content_type = models.ForeignKey(
        ContentType,
        models.SET_NULL,
        verbose_name=_('content type'),
        blank=True, null=True,
    )
    object_id = models.TextField(_('object id'), blank=True, null=True)
    # Translators: 'repr' means representation (https://docs.python.org/3/library/functions.html#repr)
    object_repr = models.CharField(_('object repr'), max_length=200)
    action_flag = models.PositiveSmallIntegerField(_('action flag'))
    # change_message is either a string or a JSON structure
    change_message = models.TextField(_('change message'), blank=True)

    objects = AdminLogEntryManager()

    class Meta:
        verbose_name = _('log entry')
        verbose_name_plural = _('log entries')
        db_table = 'app_admin_log'
        ordering = ('-action_time',)

    def __repr__(self):
        return str(self.action_time)

    def __str__(self):
        if self.is_addition():
            return gettext('Added "%(object)s".') % {'object': self.object_repr}
        elif self.is_change():
            return gettext('Changed "%(object)s" - %(changes)s') % {
                'object': self.object_repr,
                'changes': self.get_change_message(),
            }
        elif self.is_deletion():
            return gettext('Deleted "%(object)s."') % {'object': self.object_repr}

        return gettext('LogEntry Object')

    def is_addition(self):
        return self.action_flag == ADDITION

    def is_change(self):
        return self.action_flag == CHANGE

    def is_deletion(self):
        return self.action_flag == DELETION

    def get_change_message(self):
        """
        If self.change_message is a JSON structure, interpret it as a change
        string, properly translated.
        """
        if self.change_message and self.change_message[0] == '[':
            try:
                change_message = json.loads(self.change_message)
            except ValueError:
                return self.change_message
            messages = []
            for sub_message in change_message:
                if 'added' in sub_message:
                    if sub_message['added']:
                        sub_message['added']['name'] = gettext(sub_message['added']['name'])
                        messages.append(gettext('Added {name} "{object}".').format(**sub_message['added']))
                    else:
                        messages.append(gettext('Added.'))

                elif 'changed' in sub_message:
                    sub_message['changed']['fields'] = get_text_list(
                        sub_message['changed']['fields'], gettext('and')
                    )
                    if 'name' in sub_message['changed']:
                        sub_message['changed']['name'] = gettext(sub_message['changed']['name'])
                        messages.append(gettext('Changed {fields} for {name} "{object}".').format(
                            **sub_message['changed']
                        ))
                    else:
                        messages.append(gettext('Changed {fields}.').format(**sub_message['changed']))

                elif 'deleted' in sub_message:
                    sub_message['deleted']['name'] = gettext(sub_message['deleted']['name'])
                    messages.append(gettext('Deleted {name} "{object}".').format(**sub_message['deleted']))

            change_message = ' '.join(msg[0].upper() + msg[1:] for msg in messages)
            return change_message or gettext('No fields changed.')
        else:
            return self.change_message

    def get_edited_object(self):
        """Return the edited object represented by this log entry."""
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def get_admin_url(self):
        """
        Return the admin URL to edit the object represented by this log entry.
        """
        if self.content_type and self.object_id:
            url_name = 'admin:%s_%s_change' % (self.content_type.app_label, self.content_type.model)
            try:
                return reverse(url_name, args=(quote(self.object_id),))
            except NoReverseMatch:
                pass
        return None
```

2. In my app's admin.py I created a class that inherits from admin.ModelAdmin and I use this class to inherit from in all the models I want the staff users to be able to change. In this class I override the log_addition, log_change and log_deletion methods. Again, I just took django code and adjusted it to my need. Here's a piece of the code on my admin.py:

```
def get_content_type_for_model(obj):
    # Since this module gets imported in the application's root package,
    # it cannot import models from other applications at the module level.
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

class MyModelAdmin(admin.ModelAdmin):
    def log_addition(self, request, object, message):
        """
        Log that an object has been successfully added.

        The default implementation creates an admin LogEntry object.
        """
        from apps.myapp.models.AdminLogEntry import AdminLogEntry, ADDITION
        return AdminLogEntry.objects.log_action(
            user_id=request.user.pk,
            content_type_id=get_content_type_for_model(object).pk,
            object_id=object.pk,
            object_repr=str(object),
            action_flag=ADDITION,
            change_message=message,
        )

    def log_change(self, request, object, message):
        """
        Log that an object has been successfully changed.

        The default implementation creates an admin LogEntry object.
        """
        from apps.myapp.models.AdminLogEntry import AdminLogEntry, CHANGE
        return AdminLogEntry.objects.log_action(
            user_id=request.user.pk,
            content_type_id=get_content_type_for_model(object).pk,
            object_id=object.pk,
            object_repr=str(object),
            action_flag=CHANGE,
            change_message=message,
        )

    def log_deletion(self, request, object, object_repr):
        """
        Log that an object will be deleted. Note that this method must be
        called before the deletion.

        The default implementation creates an admin LogEntry object.
        """
        from apps.myapp.models.AdminLogEntry import AdminLogEntry, DELETION
        return AdminLogEntry.objects.log_action(
            user_id=request.user.pk,
            content_type_id=get_content_type_for_model(object).pk,
            object_id=object.pk,
            object_repr=object_repr,
            action_flag=DELETION,
        )
```

It should work out of the box after running makemigrations and migrate_schemas.

**Comment by saileshkush95** [comment]
> Or, even better (I was too curious):
> 
> A Django AdminSite subclass that filters the displayed apps to match the current tenant. For this to work, you need a way to determine if the current tenant is public. I do not use the default subdomain-tenant-approach (mine is cookie-based), so you have to make up something here.
> 
> The result of this approach is an admin site that displays either public or shared apps, whatever is appropriate, all under a single admin URL.
> 
> My TenantModel (called Project) has a class method `current_is_public` that is used by the following code. You'll have to adopt this to your (probably subdomain-based) implementation.
> This is the AdminSite subclass that filters apps (file is named 'tenant_admin.py'):
> 
> ```
> # -*- coding: utf-8 -*-
> from __future__ import unicode_literals
> 
> from django.contrib import admin
> from django.conf import settings
> from .models import Project  # your TenantModel here
> 
> 
> class TenantAwareAdminSite(admin.AdminSite):
> 
>     def get_app_list(self, request):
>         """ override to return only the apps that are appropriate - tenant aware or public """
>         # check if current schema is public
>         is_public = Project.current_is_public(request)
> 
>         app_list = super(TenantAwareAdminSite, self).get_app_list(request)
>         tenant_aware_apps = []
> 
>         for app in app_list:
>             if is_public:
>                 if app["app_label"] in settings.SHARED_APPS:
>                     tenant_aware_apps.append(app)
>             else:
>                 if app["app_label"] in settings.TENANT_APPS:
>                     tenant_aware_apps.append(app)
> 
>         return tenant_aware_apps
> 
> 
> # tenant aware admin site singleton
> admin_site = TenantAwareAdminSite(name="admin")
> ```
> 
> In your apps' admin.py, you do not register with the default admin.site, but the tenant-aware site instance like this:
> 
> ```
> from django.contrib import admin
> 
> from .models import Project  # any model class
> from .tenant_admin import admin_site  # adopt to the file where your TenantAwareAdminSite is
> 
> 
> class ProjectAdmin(admin.ModelAdmin):
>     [...]
> 
> admin_site.register(Project, ProjectAdmin)
> ```
> 
> Then, in you project's base urls.py:
> 
> ```
> from projects.tenant_admin import admin_site  # this is my import path to the tenant aware admin site
> 
> urlpatterns = [
>     url(r'^admin/', admin_site.urls),
> 
>     [...],
> ]
> ```

I'm trying to implement your solutions but i'm facing some error like this
![DeepinScreenshot_select-area_20200330111644](https://user-images.githubusercontent.com/28560875/77878418-f5478080-7277-11ea-93c3-7f2919d94ce2.png)

here is my client model
```
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until = models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)
    is_public = models.BooleanField(default=False)

    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True

    @classmethod
    def current_is_public(cls, request):
        client = cls.get_current(request)

        return client and client.is_public

```
