### ISSUE TITLE
Doesn't work with Postgresql extensions (hstore) 

### ISSUE THREAD

**Issue by owais** [bernardopires/django-tenant-schemas#113]
Tenant models fail to sync if they try to use postgresql's hstore field.  It seems hstore functions are not visible to the sync command. The hstore extensions are installed in the public schema.

**Comment by davidmir** [comment]
Hi,

I created a schema 'extensions' that has installed postgis. I also added in the settings files PG_EXTRA_SEARCH_PATHS = ['extensions'].

However when I run the migration it gives me the following error:

'django.db.utils.ProgrammingError: type "geometry" does not exist'

If I install postgis extension in one of the tenant schemas this error no longer occurs and all migrations run successfully.

This means that he is ignoring the schema added in PG_EXTRA_SEARCH_PATHS?

Thanks in advance

**Comment by philfriesen** [comment]
Just add all extensions to the “public” schema in Postgres. We did this for hstore and it works great! --Phil.

**Comment by davidmir** [comment]
It gives the same error with the extension in the public schema.

**Comment by owais** [comment]
Can you try to execute a query in postgresql shell that uses postgis
extension after setting `search_path` to extensions? If it works, then the
bug is in tenant-schemas.

@philfriesen, it is not recommended to add extensions to public. They'll
not be always available. For example, when migrating private schemas only
or when you want the query to run only on a private schema aka
seach_path=your_private_schema. Any calls to hstore functions will fail at
such times. It is better to create a dedicated schema for extensions and
always keep it on search_path.

**Comment by davidmir** [comment]
It works. Now the PG_EXTRA_SEARCH_PATHS does not work in the current version, gives: django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by davidmir** [comment]
Has anyone used the PostGIS in version 1.5.5?
