### ISSUE TITLE
Apps imported twice when in both SHARED_APPS and TENANT_APPS

### ISSUE THREAD

**Issue by owais** [bernardopires/django-tenant-schemas#114]
Using an app in both SHARED_APPS and TENANT_APPS imports the app twice registering things like signals and search_indexes (haystack) twice breaking integration with these libs/apps.

My use case is a simple one. Each tenant has it's own table for users which depends on django's auth app. The main site also has it's own user table powered by the same app. As a result, I've to add my 'users' app to both `SHARED_APPS` (for main site) and `TENANT_APPS`. This works but imports the given app twice.

P.S.

I guess a fix for this will take some time and probably a lot of discussion. In the meanwhile, can I mitigate this issue by creating the main site as a tenant (separate schema, not public) but on root domain instead of subdomain? Will this cause any issues?

**Comment by vinitkumar** [comment]
@owais Are you able to run your haystack with django tenant schemas?
