### ISSUE TITLE
Separate Django Administration components?

### ISSUE THREAD

**Issue by dkvdm** [bernardopires/django-tenant-schemas#123]
I have a public site and tenants, both are using the Django administration panel by adding django.contrib.admin to SHARED_APPS.
When I admin.site.register a Model in the tenant app, it will show up in the administration panel of the public AND tenant site.

As this model doesn't exist on public, how can I make sure it will not register on the administration panel?

Thanks!

**Comment by JeansReal** [comment]
Is there any workaround for this ?
