### ISSUE TITLE
How to do loaddata foo.json --tenant ?

### ISSUE THREAD

**Issue by cfpperche** [bernardopires/django-tenant-schemas#152]
I'm trying to create the command loaddata "foot.json" --tenant, however I am not having success. 

Would have any tips on how to do this? 

Thank you

**Comment by ramses132** [comment]
I am trying to do this and django 2.0 says me TypeError: Unknown option(s) for loaddata command: schema_name, skip_public. Valid options are: app, app_label, args, database, exclude, format, help, ignore, ignorenonexistent, no_color, pythonpath, settings, skip_checks, stderr, stdout, traceback, verbosity, version.

**Comment by thelinuxer** [comment]
This worked for me with Django 2.0
Hope it helps.

```
from tenant_schemas.management.commands import TenantWrappedCommand
from django.core.management.commands import loaddata

class Command(TenantWrappedCommand):
    COMMAND = loaddata.Command
```

**Comment by alexandrebarbaruiva** [comment]
And how do I load fixtures to `public`?

**Comment by danribeiro** [comment]
https://django-tenant-schemas.readthedocs.io/en/latest/use.html#management-commands
