### ISSUE TITLE
IOError at sync_schema

### ISSUE THREAD

**Issue by fproldan** [bernardopires/django-tenant-schemas#199]
Hi, i have a form where the users can to create a tenant, but where the tenant call save method i get an [Errno 5] Input/output error.
Any clue of what i'm doing wrong?

The view:

``` python
class DemoView(FormView):
    template_name = 'demo.html'
    form_class = DemoForm

    def get_success_url(self):
        return 'http://'+self.url+'/jardin/'

    def form_valid(self, form):
        nombre = (form.cleaned_data.get('nombre')).replace(' ','').lower()
        self.url = nombre + '.' + settings.SITE_URL
        tenant = Client(domain_url=self.url,
                        schema_name=nombre,
                        nombre=nombre,
                        paid_until='2014-12-05',
                        on_trial=True)
        tenant.save()
        usuarioAdmin = form.cleaned_data.get('dni')
        passwordAdmin = form.cleaned_data.get('password1')
        datosPrueba = form.cleaned_data.get('datosPrueba')

        with tenant_context(tenant):
            CustomUser.objects.create_superuser(num_doc=usuarioAdmin, password=passwordAdmin)
            s = Site(domain=self.url,name=nombre)
            s.save()

            if datosPrueba:
                call_command('load_schema_data', 'sala.json', schema_name=nombre, verbosity=0,)
        return super(DemoView, self).form_valid(form)

```

The tracebak:

Django Version: 1.6.2
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.comments',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'south',
 'registration',
 'easy_pdf',
 'tinymce',
 'students',
 'finance',
 'efinance',
 'eventos',
 'college',
 'tagging',
 'mptt',
 'zinnia',
 'schedule',
 'tenant_schemas',
 'bootstrap3',
 'jardin',
 'crispy_forms',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.contenttypes',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'students',
 'finance',
 'efinance',
 'eventos',
 'college',
 'tagging',
 'mptt',
 'zinnia',
 'schedule',
 'tenant_schemas',
 'bootstrap3',
 'jardin',
 'south',
 'crispy_forms',
 'tenant_schemas')
Installed Middleware:
('tenant_schemas.middleware.TenantMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/home/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/home/env/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
2.             return self.dispatch(request, _args, *_kwargs)
   File "/home/env/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
3.         return handler(request, _args, *_kwargs)
   File "/home/env/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
4.             return self.form_valid(form)
   File "/home/persis/edujango/efinance/views.py" in form_valid
5.         tenant.save(verbosity=0)
   File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/models.py" in save
6.             self.create_schema(check_if_exists=True, verbosity=verbosity)
   File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/models.py" in create_schema
7.                          verbosity=verbosity,
   File "/home/env/local/lib/python2.7/site-packages/django/core/management/**init**.py" in call_command
8.     return klass.execute(_args, *_defaults)
   File "/home/env/local/lib/python2.7/site-packages/django/core/management/base.py" in execute
9.             output = self.handle(_args, *_options)
   File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/management/commands/sync_schemas.py" in handle
10.             self.sync_tenant_apps(self.schema_name)
    File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/management/commands/sync_schemas.py" in sync_tenant_apps
11.             self._sync_tenant(tenant)
    File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/management/commands/sync_schemas.py" in _sync_tenant
12.         self._notice("=== Running syncdb for schema: %s" % tenant.schema_name)
    File "/home/env/local/lib/python2.7/site-packages/tenant_schemas/management/commands/__init__.py" in _notice
13.         self.stdout.write(self.style.NOTICE(output))
    File "/home/env/local/lib/python2.7/site-packages/django/core/management/base.py" in write
14.         self._out.write(force_str(style_func(msg)))

Exception Type: IOError at /demo/
Exception Value: [Errno 5] Input/output error

Thanks!

**Comment by kskumar** [comment]
@fproldan what did you do to fix it? I am having the exact same problem on a CentOS 7 AWS server (code works fine on my laptop w/ development server). Python 2.7.11, Django 1.9, django-tenant-schemas 1.5.7, gunicorn 19.3.0, nginx 1.9.9.

**Comment by kskumar** [comment]
In my case, I was being lazy and starting gunicorn like this:

    $ ssh myserver
    $ source /path/to/env/bin/activate
    $ gunicorn -c /path/to/gunicorn_config.py myApp.wsgi:application &
    $ deactivate
    $ exit

By starting gunicorn this way, it uses the SSH session's terminal session for output. Once you exit the SSH session, there is no longer a place for the output from `tenant.save()` to go, and this error is produced.

Ultimately, this issue can be solved by using supervisord to manage your gunicorn processes, which seems like the preferred way to do things in the Django world.
