### ISSUE TITLE
Use Django Admin?

### ISSUE THREAD

**Issue by CARocha** [bernardopires/django-tenant-schemas#218]
Hi, i use django 1.7.2, and follow example tutorial all is ok is working for generate user list,
but a try activate admin django
but is imposible log in, i create my super user, and other thing is a put in urls_tenants.py
the activate admin is correct?

is posible use the django admin? with tenant?

Cheers

**Comment by bernardopires** [comment]
Did you create your super user at the correct schema? It should be possible to use django admin with tenant.
