### ISSUE TITLE
Is the PIP version updated from this repo?

### ISSUE THREAD

**Issue by fellipeh** [bernardopires/django-tenant-schemas#219]
Is the PIP version updated from this repo?

I want to try in my project, but I need to work in Python3 and Django 1.7

Cheers

**Comment by bernardopires** [comment]
Yes, the pip version is the latest version.

Are you getting errors with python3?

**Comment by fellipeh** [comment]
No just ask, before I install :)

Another question: using this app,I have auth models - completely separated for each sub-domain?

**Comment by bernardopires** [comment]
Yes you do
