### ISSUE TITLE
public model need a domain_url? Why?

### ISSUE THREAD

**Issue by fellipeh** [bernardopires/django-tenant-schemas#221]
Hi! 

I`m try to understand this app, and if I'm not doing wrong.. I have one model, name: Cidade. This is a public model, all tenant can use these model.

Can I think correctly?  I yes, doesn't work..  because I have these model:

```python
class Cidade(TenantMixin):
    status = models.CharField(u'Status', max_length=1, default='A', choices=Ativo_Inativo_CHOICE)
    descricao = models.CharField(u'Descrição', max_length=70)
    uf = models.CharField(u'Estado', max_length=2, choices=Estados_CHOICE)
    cod_municipio = models.IntegerField(u'Cod. municipio')
    cod_estado = models.IntegerField(u'Cod. Estado')
    pais = models.CharField(u'País', max_length=50)
    cod_pais = models.IntegerField(u'Cod. País')

    class Meta:
        ordering = ['uf', 'descricao']

    def __str__(self):
        return self.descricao + ' / ' + self.uf
```
when I try to include some record with sql file, errors appears like these:
 
Failed to install custom SQL for core_public.Cidade model: null value in column "domain_url" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, A, NOVA BRASILÂNDIA D'OESTE, RO, 1100148, 11, BRASIL, 1058).

**Comment by bernardopires** [comment]
If it's a public model it shouldn't inherit `TenantMixin`. Only your single tenant model (which controls the routing) should inherit it.

**Comment by fellipeh** [comment]
Thanks man! That's was I thought, but I make a confusion reading the docs..
