### ISSUE TITLE
Error on creating non-public schema with 1.5.1

### ISSUE THREAD

**Issue by m4l** [bernardopires/django-tenant-schemas#226]
I'm getting an error now when setting up my test environment after upgrading from 1.4.8 to 1.5.1 on Django 1.6, it looks like this:

    sudo -u postgres createdb mydb
    ./manage.py sync_schemas --shared
    ./manage.py runscript demo_schemas

demo_schemas.py:

    from middleware.apps.schemas.models import Schema  # my tenant model

    def run():
        Schema.objects.create(domain_url='mypage.com', schema_name='public', name='My Page')
        Schema.objects.create(domain_url='someone.mypage.com', schema_name='someone', name='Someone')

Public schema is created fine, the 2nd one also gets created but fails with:

		/home/dev/envs/py26/lib/python2.6/site-packages/django/db/backends/util.pyc in execute(self, sql, params)
		 51                 return self.cursor.execute(sql)
		 52             else:
	---> 53                 return self.cursor.execute(sql, params)
		 54 
		 55     def executemany(self, sql, param_list):

	ProgrammingError: relation "schemas_schema" does not exist
	LINE 1: DELETE FROM "schemas_schema" WHERE "id" IN (1)

I'm not sure if it's my code or not, I have disabled all signal handler which may interfere. Does the DELETE query indicate that something went wrong earlier and it's trying to revert the CREATE but in the wrong schema?

**Comment by morgendagen** [comment]
I ran into this same issue a few days ago. For me the problem turned out to be a missing module in version 1.5.1 downloaded from PyPI (issue #224). Installing 1.5.1-4-g45c9ee9 fixed it.

**Comment by bernardopires** [comment]
If downloading the new PyPi version doesn't work, try calling `connection.set_schema_to_public()` after saving the first schema.

**Comment by m4l** [comment]
Thanks for the help, I reinstalled from pypi and added the line but still get the same error :-/
