### ISSUE TITLE
Domain URLs

### ISSUE THREAD

**Issue by gfronza** [bernardopires/django-tenant-schemas#233]
HI Bernardo!

This issue is regarding a question I have about the behavior of django-tenant-schemas. So here I go:

Let's say I have an application running under the domain foo.com. Some new clients want to have their own database, without sharing data with others (tenants). The thing is that these clients would like to access the application through their own domain, something like 'foo.client.com'. Reading the project docs I noticed that the regular use case is to have the shared (public) as the main domain and the tenants as subdomains. My question is: can I set fully customized domains to my tenants? How would the django-tenant-schemas use the public schema to read info of the given tenant? Should I use PG_EXTRA_SEARCH_PATHS for that?

Thanks in advance.

**Comment by bernardopires** [comment]
Do you want a separate schema or database for each tenant? The latter is not supported.

The routing uses hostnames, so it really doesn't matter if it's `subdomain.domain.com` or just `client.com`. So yes, each tenant can be a different domain, it will work as long as your server is routing all these domains to the same django project. Hope this makes sense.

**Comment by gfronza** [comment]
That's great! I will be using a schema for each tenant (I just said "database" before because it's how the client sees). Thanks for your help.
