### ISSUE TITLE
Problem on pip freeze

### ISSUE THREAD

**Issue by emanuelcds** [bernardopires/django-tenant-schemas#235]
There is a problem when using pip freeze for generating a requirements.txt with django-tenant-schemas version. It needs to use the pypi version for further maintenance, updates and installation, but when you install it using pip it uses the git version instead.

pip freeze output:

django-tenant-schemas==cfde0c

**Comment by m4l** [comment]
I can't confirm that. I get:

    pip install django-tenant-schemas
    pip freeze|grep tenant
    django-tenant-schemas==1.5.2

**Comment by emanuelcds** [comment]
django-tenant-schemas==cfde0c

josecoelho [4:06 PM]4:06
pip freeze output

josecoelho [4:08 PM]
Downloading/unpacking django-tenant-schemas==cfde0c (from -r requirements.txt (line 6))
 Could not find a version that satisfies the requirement django-tenant-schemas==cfde0c (from -r requirements.txt (line 6)) (from versions: .1.4.0-6-g65571f2, .1.4.0, .1.4.3-1-g2e69cc8, .1.4.3, 1.0.0, 1.0.1-5-g8c33028, 1.0.1, 1.0.2-1-g8c85b44, 1.0.3, 1.1.0, 1.1.1, 1.1.2-1-gf4db705, 1.1.2, 1.1.3, 1.1.5, 1.2.0, 1.3.0-3-g7363e2b, 1.3.1, 1.3.2, 1.4.1-2-g6407150, 1.4.1, 1.4.4, 1.4.5, 1.4.6-1-ga6e682d, 1.4.6, 1.4.7, 1.4.8, 1.5.0-2-g5c6d374, 1.5.0-5-g3c2c786, 1.5.1-4-g45c9ee9, 1.5.1, 1.5.2, v1.0.1)\

**Comment by emanuelcds** [comment]
We realized that the project has a git version task for updating the package version. Please check the 1.5.2 package version on PyPI.

**Comment by m4l** [comment]
If you want latest stable release just change the line in your requirements.txt:

    django-tenant-schemas==1.5.2

If you want a certain git commit follow the instructions here:
http://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

I have no idea how pip freeze would give you a version such as 'cfde0c'. Never seen that before.

**Comment by bernardopires** [comment]
That might have happened when I pushed a new version to pypi without creating a new version on git.
