### ISSUE TITLE
shared login sessions

### ISSUE THREAD

**Issue by wiel** [bernardopires/django-tenant-schemas#238]
after logging into the public tenant and then navigating to a non public tenant, I noticed that I am not logged into the non public tenant. is that normal behavior when sharing auth?

    DATABASES = {
        'default': {
            'ENGINE': 'tenant_schemas.postgresql_backend', 
            'HOST': '',
            'PASSWORD': '',
            'NAME': '',
            'USER': '',
            'PORT': '5432',
        }
    }

    DATABASE_ROUTERS = (
        'tenant_schemas.routers.TenantSyncRouter',
    )

    MIDDLEWARE_CLASSES = (
        'tenant_schemas.middleware.TenantMiddleware',
        )

    SHARED_APPS = [
        'tenant_schemas',  # mandatory
        # you must list the app where your tenant model resides in
        'custom',

       'django.contrib.contenttypes',
       'django.contrib.auth',

        # everything below here is optional
        'django.contrib.sessions',
        'django.contrib.sites',
        'django.contrib.messages',
        'django.contrib.admin',
        'django.contrib.staticfiles',
        'django.contrib.admindocs',
        'django.contrib.flatpages',
    ] 

    TENANT_APPS = [
        # The following Django contrib apps must be in TENANT_APPS
        'django.contrib.contenttypes',

        # 3rd-party apps that oscar depends on

        # your tenant-specific apps

    ] 

    INSTALLED_APPS = SHARED_APPS + TENANT_APPS + ['tenant_schemas',] 

    TENANT_MODEL = "custom.Client"

**Comment by bernardopires** [comment]
Sounds like a cookie issue. https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-SESSION_COOKIE_DOMAIN

Let me know if it doesn't work.

**Comment by wiel** [comment]
yes it worked. it was a cookie issue, thank you

**Comment by coler-j** [comment]
This should be added to the docs of this library.
