### ISSUE TITLE
Error was: cannot import name get_public_schema_name

### ISSUE THREAD

**Issue by aijogja** [bernardopires/django-tenant-schemas#239]
When I run this command, got an error *'tenant_schemas.postgresql_backend' isn't an available database backend*

command:
```
python manage.py sync_schemas --shared
```
error:
> ImproperlyConfigured: 'tenant_schemas.postgresql_backend' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: cannot import name get_public_schema_name

I used Django==1.5.4 and django-tenant-schemas==1.5.2

Thanks

**Comment by bernardopires** [comment]
Is `tenant_schemas` on your `INSTALLED_APPS` setting?

**Comment by aijogja** [comment]
of course.

```
SHARED_APPS = (
    ...
    'tenant_schemas',
)

INSTALLED_APPS = SHARED_APPS + TENANT_APPS + ('tenant_schemas',)
```

**Comment by aijogja** [comment]
when I try to test, got an error "cannot import name connection"
```
python manage.py test
```
> ImproperlyConfigured: Error importing database router TenantSyncRouter: "cannot import name connection"

**Comment by duarteangelo** [comment]
Hi, this problem is occurring with me.

I use:
Django = 1.7.4
django-tenant-schemas = 1.5.2


    SHARED_APPS = (
        'tenant_schemas',  # mandatory
        'src.cliente',
        
        ...
    )

    TENANT_APPS = (
        ...
        
        
    )

    TENANT_MODEL = "cliente.Cliente"  # app.Model

    if django.VERSION >= (1, 7, 0):
        INSTALLED_APPS = list(set(TENANT_APPS + SHARED_APPS))
    else:
        INSTALLED_APPS = TENANT_APPS + SHARED_APPS + ('tenant_schemas',)



The exception:

    raise ImproperlyConfigured(error_msg)
    django.core.exceptions.ImproperlyConfigured: 'tenant_schemas.postgresql_backend' isn't an available database backend.
    Try using 'django.db.backends.XXX', where XXX is one of:
        u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
    Error was: cannot import name get_public_schema_name

**Comment by duarteangelo** [comment]
On my server was running Django 1.5. I installed the latest version, but Django 1.5 was running

I solved the problem by reinstalling the python and django

**Comment by honur** [comment]
I faced the same issue too when running
python manage.py sync_schemas --shared

It seems it occurs because of circular import. I fixed it by editing the file tenant_schemas/utils.py and moving the lines

from django.db import connection
from django.db.models.loading import get_model
 
inside the functions they are used

After it sync_schemas ran successfully. 
BTW, after successful run, running sync_schemas again is giving me error
AttributeError: 'DatabaseSchemaIntrospection' object has no attribute 'ignored_tables'

Is this correct behavior ?

**Comment by honur** [comment]
Ok, I figured out the error:
AttributeError: 'DatabaseSchemaIntrospection' object has no attribute 'ignored_tables'

The thing is I am using django 1.5. ignored_tables were introduced in django 1.6 only. So there should be a version check before using it.

**Comment by bernardopires** [comment]
Sorry, no support for django 1.5. Will update requirements.

**Comment by rjdp** [comment]
in case someone dealing with legacy code and facing this issue, use [this](https://gist.github.com/rjdp/b5d377c535cf72c040d0c2c9396f6de1#file-tenant_schemas-diff) patch for tenant_schemas
