### ISSUE TITLE
How to handle schema with different users and pages?

### ISSUE THREAD

**Issue by VijeshVenugopal** [bernardopires/django-tenant-schemas#242]
Hi,

I have implemented django tenant schema package in my project.But something stopped me from going further. First of all,  i have a domain named "example.com" and we can register users from front end and can also add users from back end. If i signup with a user named "test", then a domain named "test.example.com" has been created. My requirement is that it should have separate schema for users section and page section ie if we are accessing "test.example.com", we should only see its own users and pages. For that, i added django-auth and pages in TENANT_APPS. But after that i cant login. Can anyone suggest me a way to accomplish this task?

**Comment by m4l** [comment]
When you process the signup request on example.com you create a new tenant, right? Afterwards you have to switch the database connection's tenant and then create a user. That way the record is created in the tenant's schema. 

    from django.db import connection
    connection.set_tenant(new_tenant)
    User.objects.create(...)
