### ISSUE TITLE
Cannot create users when Wagtail is installed

### ISSUE THREAD

**Issue by RasmusKlett** [bernardopires/django-tenant-schemas#244]
I am trying to get Wagtail CMS to handle the public schema urls, with tenant-schemas taking care of some other apps. Tenant-schemas seems to be configured correctly, and Wagtail too, but when I add a non-public tenant, the migrations for Wagtail fail. 
Specifically, wagtailcore.0002_initial_data.py fails. It is trying to insert an initial Page into the page table, and failing saying it is trying to insert a null value into a non-null column. It seems this colum is not created until the wagtailcore.0003 migration, so maybe it is trying to insert into the already-created public table for Wagtail? 
I am not sure I understand why it even needs to run the Wagtail migrations for the tenant, since Wagtail is in my shared apps, and so as I understand it should live in the public schema anyway.

**Comment by bernardopires** [comment]
Are you still having this issue?

**Comment by RasmusKlett** [comment]
I gave up on it. I'm hoping my application can take the performance hit of keeping everything in the same table, so I'm no longer using tenant-schemes, unfortunately. Might take a second look if this gets fixed, but I cannot retry and troubleshoot right now.

**Comment by bernardopires** [comment]
Alright, I'll close this for now as it seems like not many other people are using Wagtail. If anyone has the time to troubleshoot this we can reopen and work on it.
