### ISSUE TITLE
TenantMixin.save doesn't respect verbosity=0

### ISSUE THREAD

**Issue by samgre** [bernardopires/django-tenant-schemas#245]
Hi,

I'd like to have a clean output when running unit tests. To do that, I create tenants with verbosity=0. The output is almost silent, with the exception of notice messages `"=== Running syncdb for `...

This could be fixed by changing the _notice method in `tenant_schemas/management/commands/__init__.py` to

    def _notice(self, output):
        if int(self.options.get('verbosity', 1)) >= 1:
            self.stdout.write(self.style.NOTICE(output))

Won't submit a pull request since, I'm not sure if this is the best way of fixing it.

**Comment by bernardopires** [comment]
Does your fix actually work? The problem is that the correct verbosity has to be passed to the `save` method of the tenant.
