### ISSUE TITLE
PublicTenantTestCase

### ISSUE THREAD

**Issue by pedrokiefer** [bernardopires/django-tenant-schemas#246]
I think a PublicSchemaTestCase is needed for testing custom PUBLIC_SCHEMA_URLCONF's. I've added it to my project, so I can test public facing views now.

But this got me thinking, wouldn't it be better if ROOT_URLCONF be the public urlconf, as it's usually in Django, and have a TENANT_URLCONF for all tenants? I think it makes sense, and avoid the errors I was getting before creating a PublicSchemaTestCase, ie. 'ProgrammingError: relation "asdf" does not exists'. The error I was expecting was a 404, as I haven't add the url mapping to PUBLIC_SCHEMA_URLCONF, and I was using django's TestCase - ie. with no tenant set.

**Comment by bernardopires** [comment]
I think in the past `ROOT_URLCONF` was the pubic URLs but eventually I changed it, not sure why anymore. I don't think either way is better, but to me it sounds more intuitive as it is now. Tenants are really the core of the app so to me it somehow makes sense that the default setting refers to the tenants urls.

To test the public facing views you should be able to run a regular django test without using anything special as django will automatically sync the public schema when running tests (if I remember correctly).

**Comment by nikhiln** [comment]
@pedrokiefer Can you please share code for `PublicSchemaTestCase` ?

**Comment by surfer190** [comment]
I don't think the public schema is synced in a normal `TestCase`, I get an empty queryset:

```
ipdb> Client.objects.all()
<TenantQueryset []>
```

Even you create it manually though, it will not use the public urls from `PUBLIC_SCHEMA_URLCONF` and you may get an error like:

`django.urls.exceptions.NoReverseMatch: 'customers' is not a registered namespace`
