### ISSUE TITLE
Include schema in log messages

### ISSUE THREAD

**Issue by quietlyconfident** [bernardopires/django-tenant-schemas#248]
It would be nice to be able to include the tenant in log messages. It seems like the way to do this would be to create a Django logging formatter object.

Has anyone implemented something like this in production?

**Comment by regolith** [comment]
This can be pretty simply done with a logging filter:

Create `app_logging.py` somewhere:
```
from django.db import connection

class TenantContextFilter(object):
    """Adds the current tenant's ``schema_name`` and ``domain_url`` properties to all log messages."""
    def filter(self, record):
        record.schema_name = connection.schema_name
        record.domain_url = getattr(connection.tenant, 'domain_url', None)
        return True
```
and in settings.py:
```
LOGGING = {
    ...
    'formatters': {
        'default': {
            'format': '%(asctime)s [%(levelname)s] [%(schema_name)s / %(domain_url)s] %(name)s: %(message)s',
        },
    },
    'filters': {
        'tenant_context': {
            '()': 'app_logging.TenantContextFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            'filters': ['tenant_context'],
        },
    },
    ...
}
```

Will output something like:

`13:29 [DEBUG] [my_schema / my-domain.myapp.dev] django.db.backends: (0.001) SELECT ...`

**Comment by bernardopires** [comment]
That's awesome @regolith! Thanks!

**Comment by AlexvEck** [comment]
Hi @goodtune, This filter is awesome. we can close this issue :D

**Comment by goodtune** [comment]
Added in d9ce4ff9.

**Comment by nsirbu** [comment]
It doesn't work for me. It says ValueError: Unable to configure filter 'tenant_context': Cannot resolve 'django_tenants.TenantContextFilter': No module named 'django_tenants.TenantContextFilter'

Where should I create the app_logging.py file ?

**Comment by regolith** [comment]
If you're using django-tenants, the proper name for the filter is  'django_tenants.log.TenantContextFilter' and if you're using this project, it's
'tenant_schemas.log.TenantContextFilter' and you do not need to create your own app_logging.py for either.

**Comment by nsirbu** [comment]
Thanks, it worked.

Is it possible to create a handler that will save the logs from each schema/tenant to a different file on the disk ?

**Comment by goodtune** [comment]
Sure, you would need to write a custom handler that maintains a mapping of tenant identifiers (probably schema_name) to an actual handler that is the file for that tenant.

Have a look at https://docs.python.org/2/library/logging.html#logging.Handler.emit

This would be similar to a number of "backends" that have been written for Django (projects such as [django-email-log](https://github.com/treyhunner/django-email-log) or [django-celery-email](https://github.com/pmclanahan/django-celery-email)) which "wrap" the standard email backend API.

You might like to create a PR or create a separate project; this could be solved in a generic enough way that it could be keyed on an of the available message fields.

**Comment by nsirbu** [comment]
> Sure, you would need to write a custom handler that maintains a mapping of tenant identifiers (probably schema_name) to an actual handler that is the file for that tenant.

Could you give some more details about this ? I don't have so much experience with Django.

**Comment by goodtune** [comment]
This isn't a Django concept at all, it's a general programming one.

Write a class that keeps in its internal state a mapping of loggers. When a message arrives use route the messages to the appropriate one.

**Comment by nsirbu** [comment]
This means I have to define all the tenants, I mean a logger for each tenant . What if the tenants are created dynamically, do I have to update the logger list each time ?

**Comment by regolith** [comment]
Your custom log handler class would have to create a "real" log handler (like `logging.handlers.TimedRotatingFileHandler`) for each new tenant it sees in a log message and forward the message to it. I don't know any python package you can just install and configure to get such a handler, so you would have to write it and deal with any multi-threading issues, "too many open files" issues, etc.

Instead of separate files per tenant, I suggest using `grep`/`less` or a gui log reader with filtering (ex: [glogg](http://glogg.bonnefon.org/)) or even a log management service (ex: [loggly](https://www.loggly.com), [logdna](https://logdna.com/), [papertrail](https://papertrailapp.com/)) that can help you filter your logs.
