### ISSUE TITLE
Incorrect migration when limiting set search_path calls

### ISSUE THREAD

**Issue by bjersey** [bernardopires/django-tenant-schemas#253]
When setting TENANT_LIMIT_SET_CALLS = True, we are observing interesting (and incorrect) behavior when migrating schemas. When this value is set, we're seeing various errors in migrate_schemas (both when creating new tenants AND just running migrate_schemas directly).
To reproduce one of the issues:

* Create a tenant (all migrations should be faked and properly saved into this tenant's history properly at this point)
* Create a new empty schema migration for a tenant app
* Try to apply the migration

When trying to migrate the tenant app, you should see a South error about no migrations for a PUBLIC app.

Any help is appreciated. Thanks!

**Comment by philfriesen** [comment]
@bernardopires Hi Bernardo. We've been using tenant schemas successfully here at The Advisory Board Company. Thanks! We created the original PR for TENANT_LIMIT_SET_CALLS to improve DB performance. We later discovered that this broke migrations as my teammate Brian documented above. We hacked a workaround, but we think we owe you a new PR. We're having some difficulty locating the area of code we need to change to fix the migration problem our original PR created. Can you point us in the right direction? Thanks! --Phil.

**Comment by philfriesen** [comment]
@bernardopires Here's some more info Brian gave me:
Summary of the issue: running the migrate_schemas command (either directly or when a new tenant is created) results in errors or incorrect south_migrationhistory records
o	The problem manifests itself in two ways:
	Creating a new tenant fails; upon creating the tenant the migrations are faked, but we see an error about the tenant not having migrations for a PUBLIC app
	Upon creating a new tenant, the public.south_migrationhistory table has history of migrations from tenant apps, and the tenant’s south_migrationhistory table doesn’t have all the records that it should
o	The difference in observing the two different errors are whether or not the public.south_migrationhistory table is empty or not before creating the tenant; if it’s properly populated, we observe the first error, if it’s empty then we see the second
•	We are able to avoid all of these issues if we run migrate_schemas (or create new tenant) with TENANT_LIMIT_SET_CALLS = False
•	From our understanding, this setting just dictates whether or not the Postgres search path is set upon every database transaction

**Comment by bjs987** [comment]
@philfriesen @bernardopires 

Migrations seems to be an oddball case because the Django folks have some logic in there that explicitly closes the database connection to work around a bug in MySQL.  Because the connection is closed during the migration, the tenant schemas database wrapper doesn't realize it's search path is no longer set, hence the odd behavior.

I noted that adding the following code to class DatabaseWrapper in postgresql_backend/base.py seems to resolve the issue for the migrate_schemas command, though not certain that this is indeed the optimal fix.  I'll post in the django-tenants project as well.  Comments?  

def close(self):
        self.search_path_set = False
        super(DatabaseWrapper, self).close()
