### ISSUE TITLE
[Feature Request] - internal function to set tenant 

### ISSUE THREAD

**Issue by quietlyconfident** [bernardopires/django-tenant-schemas#258]
I see from the documentation that it is possible to set the tenant on the command line using:
`./manage.py tenant_command <some command here> --schema=<schema_name>`

However, it would be useful to be able to set / change the tenant from within a running command as well.  I understand this might produce wacky and unpredictable results in the context of a request, but I'm thinking more of management commands, celery commands, and so on.

For example, if I want to perform an operation on all the tenants in my application, I could do something like the following, assuming that it starts in the PUBLIC schema:
````
# [pseudocode]
for tenant in TenantModel.objects.all():
    if tenant.property == "some value":
        tenant_schemas.switch_tenant(tenant.schema_name)
        # Do
        # Something
        # Here
````

I see from the documentation that "Every command except tenant_command runs by default on all tenants."  So, for my "DO SOMETHING" portion of the script, I could presumably create a django management command and execute it that way.  Thats great for relatively low-setup-time commands, that definitely want to run every single tenant.; however for high-setup time commands, it would be able to do some setup before we switch through all two thousand tenants and apply the payload.  And, it makes it difficult to decide on the fly which tenants to run the command on; without doing the logic in an outer loop and spawning additional processes.

By setup time here, I mean, where the "command" requires some time to retrieve remote data, or perform some calculation, before the result can be applied.  For example, in my application, I would like to retrieve some files from a remote location; then based on those files, do some things in all the tenants.

**Comment by dvl** [comment]
That already exists

```python
from tenant_schemas.utils import get_tenant_model, tenant_context, get_public_schema_name

tenants = get_tenant_model().objects.exclude(schema_name=get_public_schema_name())

for tenant in tenants:
    with tenant_context(tenant):
        do_something()
```
