### ISSUE TITLE
[Documentation] How to Inherit from from BaseTenantCommand

### ISSUE THREAD

**Issue by quietlyconfident** [bernardopires/django-tenant-schemas#259]
It would be really helpful to have some documentation on how to create a management command using BaseTenantCommand.  Either it is broken (unlikely I think) or I'm doing it wrong (likely, I think) but it is hard to tell because I can't find an example for using it right. 

The [DTS Documentation](https://django-tenant-schemas.readthedocs.org/en/latest/use.html#management-commands) says that you can create your own commands that run on every tenant by inheriting BaseTenantCommand.

And the [Django Documentation](https://docs.djangoproject.com/en/1.7/howto/custom-management-commands/) explains how to make a management command.

So it seems natural that I could make a command just like the Django documentation says, but instead of inheriting from BaseCommand, I would inherit from BaseTenantCommand, like so:
`class Command(BaseTenantCommand):`

Unfortunately, this causes an infinite loop:
`RuntimeError: maximum recursion depth exceeded while calling a Python object`

**Comment by quietlyconfident** [comment]
It appears this is related to #255 , #254.

Merging either of those would resolve this.

**Comment by bernardopires** [comment]
#255 was merged. Thanks!
