### ISSUE TITLE
Cross schema foreign keys?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [bernardopires/django-tenant-schemas#266]
Hi, is it possible to create a foreign key FROM a table of a tenant schema TO a table of the shared schema? If yes, will related queries work normally in django?

For instance... lets say I have a table "cities" in the PUBLIC SCHEMA and a table "restaurants" in a TENANT SCHEMA... if I have a column city = models.ForeignKey(City) in my Restaurant model, will I be able to do something like this: Restaurant.objects.filter(city__name="Los Angeles")?

Thank you!

**Comment by tomturner** [comment]
Yes this is possible in fact i do it

FYI you might want to check as https://github.com/tomturner/django-tenants which is a clone of this project for django 1.8

**Comment by bernardopires** [comment]
Yes, it should work. Shared auth works.

**Comment by AustinGomez** [comment]
Hi there, sorry to resurrect and old thread.

I'm having issues doing this. When I try to do this I get the error:

insert or update on table "authenticate_user" violates foreign key constraint "authenticate_user_client_id_628ed7f1_fk_authenticate_client_id"
DETAIL:  Key (client_id)=(1) is not present in table "authenticate_client".
