### ISSUE TITLE
tenant command: No such option

### ISSUE THREAD

**Issue by windman83** [bernardopires/django-tenant-schemas#267]
Hi, tenant_command doesn't recognize wrapped command options: e.g. manage.py tenant_command some_command --some-option --schema=some_schema, gives no such option error.
Hi managed to get it working by adding
***
else:
...klass = load_command_class(app_name, argv[2])
self.option_list=list(set(self.option_list+klass.option_list))
super(Command, self).run_from_argv(argv)
***
in tenant_command.py
Thanks, very good work!!! Paolo

**Comment by tomturner** [comment]
you might he interested in the 1.8 fork of this at https://github.com/tomturner/django-tenants

However it still have the same bug and there is a ticket about it. I will be fixing it soon.
