### ISSUE TITLE
Moving apps from shared to tenants (or other way around) woudn't be picked up by migrations

### ISSUE THREAD

**Issue by ka7eh** [bernardopires/django-tenant-schemas#276]
I added some apps to my `SHARED_APPS` and migrated; afterward I decided to move them to my `TENANT_APPS`, but it wasn't picked up by django migrations and no table was created in tenants' schemas.
I believe the problem is with `ContentType`; I have this app in both `SHARED_APPS` and `TENANT_APPS`, as in the documents; it adds all models in `INSTALLED_APPS` to its tables in "all schemas", so when you want to move an app, let's say from `SHARED_APPS` to `TENANT_APPS`, it doesn't notice any changes and no migration happens, or at least that's my guess.
The follow-up question: shouldn't `ContentType` only register those apps which are withing its scope? I mean for public schema, it should only register `SHARED_APPS` and the same story for tenants?

**Comment by dimmg** [comment]
According to the settings from the django-tenant-schemas docs, the `django.contrib.contenttypes` are included in both `SHARED_APPS` and `TENANT_APPS`, therefore it will contain both apps.
The migrations for `TENANT_APPS` are automatically generated when a new tenant in the public schema is created.

**Comment by ka7eh** [comment]
@dimmg I understand that and it works for new tenants, but not for existing ones. If you create few tenants, then restructure your `TENANT_APPS` and your `SHARED_APPS`, no table will be created for the existing tenants.

**Comment by bernardopires** [comment]
So you added a new app to ``TENANT_APPS`` and it did not create the new tables? What Django version are you on? Did you run migrate or sync?

**Comment by ka7eh** [comment]
Yep, I did run migrate and it doesn't work neither on Django 1.7.* or 1.8.*
You can reproduce the problem in your example project like this:
- Finish first steps of tutorial and make one client
- Create a new app, add it to `SHARED_APPS`, then migrate
- After migration, remove your new app from `SHARED_APPS` and put it in `TENANT_APPS`, then migrate again. The expected behaviour for me is removal of new app's table from public schema and creation of its table in clients' schemas, which doesn't happen.

When you create a new client, `django_migrations` table is created in its schema with a list of all migrations (of course!), including the ones for shared apps. So, when you transfer a previously migrated app from `SHARD_APPS` to `TENANT_APPS`, Django thinks that app is already migrated for that schema.
The problem can be fixed by removing the relevant line in `django_migrations` table and then migrate. But probably it's better to implement it in `migrate_schemas` somehow.

**Comment by pengye91** [comment]
Hi @ka7eh , I am in the exactly same situation as yours, did you fix the it?

**Comment by ka7eh** [comment]
@pengye91 it was a long time ago under an older version; I can't remember the resolution, but looking at the previous comments, I assume a manual delete in `django_migrations` should work; unless they've added a workaround in the newer versions.

**Comment by pengye91** [comment]
@ka7eh I tried manually deleting migrations in database, and it worked. But I agree with you about doing that with `migrate_schemas`, thanks a lot!
