### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by elklaaso** [bernardopires/django-tenant-schemas#279]
Hi,

When will Python 3 be supported?

**Comment by bernardopires** [comment]
I don't have any concrete plans but anyone is welcome to send a pull request adding support to py3

**Comment by janza** [comment]
I've just tried running this with python 3 and tenant_tutorial example seems to be working fine.

**Comment by dszmaj** [comment]
ahhh... so this may be the problem... i try to make this work with DRF and test with pytest and when I create test tenants in fixture (straight from model, no fancy stuff), connection.schema_name gets suddenly nulled and set to previous one that is not public... exactly after first 2 successes ('public' and 'dev1', 'dev2' crushes)

python 3.5, and other errors so far

**Comment by rodolfomartinez** [comment]
+1 - also using 3.5

**Comment by bartmika** [comment]
+1

**Comment by arkanus** [comment]
I managed to run all the tests  with python 3.5, only minor modifications were needed, mostly having to do with imports and changes in modules, and all tests are passing with `tox`
