### ISSUE TITLE
transaction support

### ISSUE THREAD

**Issue by gaoyukid** [bernardopires/django-tenant-schemas#280]
Hi, 

I am from java background so some of my understanding might be wrong. but I don't see any transaction handling in the library. is it thread-safe? 

My understanding of the library is that the library will essentially execute "SET search_path TO tenant1, public;"  before any query for different tenants. However, when two users from different tenants come in in different threads, and the first user's thread sleeps right after "SET search_path", when the second user finished the request. will the first user query under the wrong search_path?

Best
Yu

**Comment by bernardopires** [comment]
Django makes a separate connection to each thread and requests don't share threads, so this shouldn't be an issue.
