### ISSUE TITLE
Is this compatible with django-rest framework?

### ISSUE THREAD

**Issue by thebarty** [bernardopires/django-tenant-schemas#283]
Hi guys,

I am planning to use django-rest framework soon and just want to ask, if this app is compatible?
 
Will ``tenant1.domain.com/api/`` will show a different data-set (and require a different login) than ``tenant2.domain.com/api/``?

Does this work? Or am I gonna run into troubles?

Kind regards
Mike

**Comment by bernardopires** [comment]
I haven't used it myself but it seems like others have used it with django-tenant-schemas.

Check https://github.com/bernardopires/django-tenant-schemas/issues?utf8=%E2%9C%93&q=rest

**Comment by fproldan** [comment]
I'm using it and it's works.

**Comment by shabda** [comment]
We are using it and it works. You will need to handle tenant/user filtering in your apiviews explicitly.
