### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by jscott1989** [bernardopires/django-tenant-schemas#284]
Is there currently a way of allowing multiple domains for a single schema (e.g. x.mysite.com and x.com).

**Comment by jscott1989** [comment]
For my own uses I solved this by adding:

additional_domains = JsonField(default=[])

to my tenant model (with JsonField coming from django_pgjson)

and then updating the middleware to:

request.tenant = TenantModel.objects.get(
                Q(domain_url=hostname) |
                Q(additional_domains__contains=hostname))

**Comment by bernardopires** [comment]
An option would be to make the schema_name non-unique in ``TenantMixin``. This should allow you to have multiple rows with different domain_urls but the same schema_name.

**Comment by juanefren** [comment]
@tomturner made a fork of this project with this functionality 
https://github.com/tomturner/django-tenants/

**Comment by mmoravcik** [comment]
+1 for this feature
