### ISSUE TITLE
Authentification for SharedApps / Public Tenant

### ISSUE THREAD

**Issue by pzv-** [bernardopires/django-tenant-schemas#286]
Hello, 

djangos default authentification (as well as all other authentification apps) make use of 'django.contrib.auth'. But if I place 'django.contrib.auth' under 'SHARED_APPS' there will only a single auth.user table for all tenants. 

Is there an easy way to authentificate users of the public tenanant without making auth.user shared by all tenants?

Thanks, Thomas

**Comment by bernardopires** [comment]
I don't think I understand your question? What exactly are you trying to do?

**Comment by KarlSayle** [comment]
Hi,

I am coming across the same issue. Currently, with 'django.contrib.auth' in 'SHARED_APPS', any user can login to any tenant just by visiting their url. However when I move 'django.contrib.auth' into 'TENNANT_APPS' I get 'ProgrammingError: relation "auth_user" does not exist' errors when creating a tenant.

Any advice would be appreciated.

Thanks,
Karl

**Comment by KarlSayle** [comment]
UPDATE

I now have the auth model working in TENANT_APPS however the issue I am now having is using a 'User' foreign key. Upon saving I receive the following error: DETAIL:  Key (user_id)=(2) is not present in table "auth_user". It appears to be trying to query the PUBLIC schema instead of the TENANT schema and obviously crashing when it doesnt find it.

**Comment by KarlSayle** [comment]
Progress...

I now have things working, sort of. If I remove all my apps from 'TENANT_APPS' leaving only the auth, content_type models the auth models are created correctly. Then if add them back in and run a migration the other models/tables are added. This allows for the previously mentions User FK.

So it seems to be the order in which the tables are built (makes sense in hindsight). Just need to 'fix' the order in which they are made.....

**Comment by KarlSayle** [comment]
Done!

After all that all I needed was to have an initial migration in the app dependent on the user table.

**Comment by bdauvergne** [comment]
It seems this issue can be closed.

**Comment by BrentLageson** [comment]
@KarlSayle 
I am having the exact same errors you were talking about. Did your solution continue to work for you? I am concerned when moving the application to AWS I will have issues with it creating migrations in the correct order.
