### ISSUE TITLE
django.contrib.auth on Tenant

### ISSUE THREAD

**Issue by andrewfam** [bernardopires/django-tenant-schemas#303]
I'm getting the following running python manage.py migrate_schemas --shared. No issues with python manage.py migrate_schemas --tenant

django.db.utils.ProgrammingError: relation "auth_user" does not exist

App settings :

SHARED_DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

EXT_APPS =(
    'allauth',
    'allauth.account',
    'crispy_forms', 
    #'debug_panel',
    #'debug_toolbar',
    'django_extensions',
    'jfu',
    'tenant_schemas',
    'werkzeug',
)

SHARED_INT_APPS = (
    'clients',
)

TENANT_DJANGO_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth'
)

TENANT_INT_APPS =(
)

SHARED_APPS = SHARED_DJANGO_APPS + EXT_APPS + SHARED_INT_APPS
TENANT_APPS = TENANT_DJANGO_APPS + TENANT_INT_APPS

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "clients.Client"

**Comment by bernardopires** [comment]
Could it be your shared allauth app is trying to reference a table in tenant?

**Comment by andrewfam** [comment]
Hey Bernard,

Thanks i think that solved it. Quick check. If i have a superuser on public would they be able to see all users including the tenants to? I may need to do some basic analytics that requires merging data across tenants.

Thanks for the input

**Comment by bernardopires** [comment]
The shared app does not have any access to the tenants by the default. But you can write code that would allow you to do what you want.
