### ISSUE TITLE
shared auth overwrites session variables

### ISSUE THREAD

**Issue by wzrd-clss** [bernardopires/django-tenant-schemas#306]
with a setup like this its possible that a user could overwrite their session variables or the same session will be used for each domain. Adding 'django.contrib.sessions' to TENANT_APPS will require the user to log in twice instead of sharing the session. is there a way to keep users logged in on more than one domain without overwriting the session?

``` python
#settings.py

SHARED_APPS = (
    'tenant_schemas', # mandatory
    'custom', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
) 

SESSION_COOKIE_DOMAIN = '.example.com'
```

**Comment by bernardopires** [comment]
I don't understand what you mean with logging in twice? Why would that be needed, didn't ``SESSION_COOKIE_DOMAIN`` work?

**Comment by wzrd-clss** [comment]
a setup like the one below will require a user to login twice when they move between domains. If I login on a domain that uses the public schema and then navigate to a domain that uses a tenant schema, I will be logged out of the public schema and also be required to login on the domain that uses the tenant schema. 

The settings in the initial post allow me to stay logged in when navigating between domains but a user's session will be shared and run the risk of overwriting session variables or causing hard to debug issues when the session variables are reused.

```python
#settings.py
SHARED_APPS = (
    'tenant_schemas', # mandatory
    'custom', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.sessions',
) 

SESSION_COOKIE_DOMAIN = '.example.com'
```

**Comment by bernardopires** [comment]
So you want the login information to be shared but not session info coming from tenants? What exactly are you afraid of being overwritten?

**Comment by wzrd-clss** [comment]
yes. I set up an e-commerce website that stores the choices that users make during checkout and I noticed that the choices were reused. Some of the choices that a user makes could cause them to skip a step in the checkout process. I am worried that this could lead to users being confused or they could unintentionally complete checkout with the wrong choices. This is just one example.

I am also worried about future changes to the site that this could be an issue for.

**Comment by bernardopires** [comment]
Why are they sharing login info? I don't know any shopping website that shares login info with others.

The other option is really to prefix your sessions with a unique token identifying the domain.

**Comment by wzrd-clss** [comment]
keeping the login info separate could be a solution to my issue as well but I think the setup below was affected by the same issue. It has been a while since I used a setup like this so I will have to test it to be sure and then reply again later 

```python
#settings.py
SHARED_APPS = (
    'tenant_schemas', # mandatory
    'custom', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
) 

SESSION_COOKIE_DOMAIN = '.example.com'
```

**Comment by bernardopires** [comment]
Make you sure you don't set ``SESSION_COOKIE_DOMAIN = None``. That will give you the standard domain cookie.
