### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by 23doors** [bernardopires/django-tenant-schemas#311]
Is 1.9 support planned? Ran into some issues e.g. some model is not found in 2nd tenant that is migrated (it works in the 1st one) which suggests some kind of internal "caching" in Django. Retrying fixes it but it's hardly a solution.

**Comment by JeancarloBarrios** [comment]
I tried to run the tutorial ind ijango 1.9 and it does not run, i had to downgrade to django 1.7

**Comment by huangweicong112** [comment]
+1
Hope 1.9 can be supported.

**Comment by JeancarloBarrios** [comment]
django-tenant seems to work so far in django 1.9. I believe it was worked from this project 
https://github.com/tomturner/django-tenants

**Comment by 23doors** [comment]
django-tenants suffers from the same issues. Having to retry for every separate tenant is hardly a working condition. Other than that, sure, it looks fine.

**Comment by 23doors** [comment]
It may have been a separate issue I was facing, same for django-tenants.

**Comment by 23doors** [comment]
Ok, sorry for all the confusion but apparently django 1.9 should work with django-tenant-schemas. Can anyone confirm that?

**Comment by JeancarloBarrios** [comment]
It did not work for me until i downgraded

Gracias por su tiempo y concideración
Jeancarlo Barrios
ACM Student Chapter Chair
CCTI vocal

**Comment by bernardopires** [comment]
What issue exactly are you guys having? I just tried it on Django 1.9 and while the tutorial was broken, it should have worked normally for regular applications. The reason it wasn't working is that migrations are now mandatory and the tutorial was missing some. I will update the documentation to remind users to run ``makemigrations``.
