### ISSUE TITLE
AttributeError: 'DatabaseWrapper' object has no attribute 'schema_name'

### ISSUE THREAD

**Issue by ojengwa** [bernardopires/django-tenant-schemas#328]
I followed the example in the documentations but I get this error:
```
File "/Users/bernard/.virtualenvs/panda/lib/python2.7/site-packages/tenant_schemas/routers.py", line 21, in allow_migrate
    if connection.schema_name == get_public_schema_name():
  File "/Users/bernard/.virtualenvs/panda/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'schema_name'
```
What could I be getting wrong, please?
:)

**Comment by mikicz** [comment]
You need to update the database engine in the settings :)

**Comment by ojengwa** [comment]
Thanks!! @mikicz

**Comment by ojengwa** [comment]
Here's my DB's default engine: 
```
'ENGINE': 'django.db.backends.postgresql',
```
I am on Django 1.9.4

**Comment by mikicz** [comment]
https://github.com/bernardopires/django-tenant-schemas/blob/master/examples/tenant_tutorial/tenant_tutorial/settings.py#L14

**Comment by ojengwa** [comment]
Thanks!!! @mikicz :)

**Comment by mehemmelbachir** [comment]
Hi guys,
i have put the same settings as the tutorial 
`'ENGINE': 'tenant_schemas.postgresql_backend',`
but i still having the same error when trying to run _migrate_schema --shared_ 
the error is:
**'DatabaseWrapper' object has no attribute 'set_schema_to_public'**

**Comment by nicolasmendoza** [comment]
@mehemmelbachir sure?, see please this tutorial and check if you have the correct settings: https://github.com/bernardopires/django-tenant-schemas/blob/master/examples/tenant_tutorial/tenant_tutorial/settings.py#L14
