### ISSUE TITLE
Single domain with multiple schemas

### ISSUE THREAD

**Issue by DanPrado** [bernardopires/django-tenant-schemas#329]
Hi.
In my company we have some scenarios where everyone using our app access the same domain (the app server domain), but have different schemas on the DB to save their specific data.
I needed a way to find the correct schema even though every request was made to the same domain.
This can be done by using a custom header on the requests called **schemaname** and extracting it from the request so we can set the correct schema (if it exists). 
I have created a `SchemaNameTenantMiddleware` that does this. I will send you a PR with the changes and would be glad to hear what you think.

**Comment by bernardopires** [comment]
Closing this issue as the discussion is happening on #330.
