### ISSUE TITLE
ImproperlyConfigured error after updating to 1.0

### ISSUE THREAD

**Issue by mrob11** [bernardopires/django-tenant-schemas#33]
I had everything working this morning then I updated to the pypi 1.0 version and ran into an error with the database engine:

```
(tenants)mike@ellie ~/sites/tenants $ ./manage.py validate
ImproperlyConfigured: 'tenant_schemas.postgresql_backend' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: No module named postgresql_backend.base
```

**Comment by rjdp** [comment]
in case someone dealing with legacy code and facing this issue, use [this](https://gist.github.com/rjdp/b5d377c535cf72c040d0c2c9396f6de1#file-tenant_schemas-diff) patch for tenant_schemas
