### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 393: ordinal not in range(128)

### ISSUE THREAD

**Issue by darkicex3** [bernardopires/django-tenant-schemas#351]
I am trying to install your app on my server with `pip3 install django-tenant-schemas` but I've got this error : 

```
tdkbs@kb-lamp-vm:/$ pip3 install django-tenant-schemas
Downloading/unpacking django-tenant-schemas
  Downloading django-tenant-schemas-1.6.2.tar.gz (288kB): 288kB downloaded
  Running setup.py (path:/tmp/pip-build-zt8f66i7/django-tenant-schemas/setup.py) egg_info for package django-tenant-schemas
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-zt8f66i7/django-tenant-schemas/setup.py", line 29, in <module>
        long_description=open('README.rst').read() if exists("README.rst") else "",
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 393: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-zt8f66i7/django-tenant-schemas/setup.py", line 29, in <module>

    long_description=open('README.rst').read() if exists("README.rst") else "",

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 393: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-zt8f66i7/django-tenant-schemas
Storing debug log for failure in /home/tdkbs/.pip/pip.log
```

**Comment by opb** [comment]
I have this exact same issue when installing in vagrant. I'm using ansible 2.1 to install in Vagrant (ubuntu 14.04). Vaguely sanitised output from ansible below:

```
<snip>
"Collecting Sphinx==1.4.1 (from -r requirements.txt (line 10))", 
"  Downloading Sphinx-1.4.1-py2.py3-none-any.whl (1.6MB)", 
"Collecting sphinx-rtd-theme==0.1.9 (from -r requirements.txt (line 11))",
"  Downloading sphinx_rtd_theme-0.1.9-py3-none-any.whl (693kB)", 
"Collecting django-cacheops==2.4.3 (from -r requirements.txt (line 13))",
"  Downloading django-cacheops-2.4.3.tar.gz", 
"Collecting django-tenant-schemas==1.6.2 (from -r requirements.txt (line 14))", 
"  Downloading django-tenant-schemas-1.6.2.tar.gz (288kB)",
"    Complete output from command python setup.py egg_info:", 
"    Traceback (most recent call last):",
"      File \"<string>\", line 1, in <module>", 
"      File \"/tmp/pip-build-6r_l0dhw/django-tenant-schemas/setup.py\", line 29, in <module>", 
"        long_description=open('README.rst').read() if exists(\"README.rst\") else \"\",", 
"      File \"/home/vagrant/ve/lib/python3.4/encodings/ascii.py\", line 26, in decode", 
"        return codecs.ascii_decode(input, self.errors)[0]", 
"    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 393: ordinal not in range(128)", 
"    ",
"    ----------------------------------------"],
```

**Comment by darkicex3** [comment]
Hi Olly,

Your UTF-8 environnement is not set propely, simply read this article :
https://perlgeek.de/en/article/set-up-a-clean-utf8-environment and you will
figure out.

For a temporary solution simply run this command before installing your
package : export LC_ALL=en_US.UTF-8

Regards,

Maxime J

Le mardi 21 juin 2016, Olly Butterfield <notifications@github.com> a écrit :

> I have this exact same issue when installing in vagrant. I'm using ansible
> 2.1 to install in Vagrant (ubuntu 14.04). Vaguely sanitised output from
> ansible below:
>
> <snip>
> "Collecting Sphinx==1.4.1 (from -r requirements.txt (line 10))",
> "  Downloading Sphinx-1.4.1-py2.py3-none-any.whl (1.6MB)",
> "Collecting sphinx-rtd-theme==0.1.9 (from -r requirements.txt (line 11))",
> "  Downloading sphinx_rtd_theme-0.1.9-py3-none-any.whl (693kB)",
> "Collecting django-cacheops==2.4.3 (from -r requirements.txt (line 13))",
> "  Downloading django-cacheops-2.4.3.tar.gz",
> "Collecting django-tenant-schemas==1.6.2 (from -r requirements.txt (line 14))",
> "  Downloading django-tenant-schemas-1.6.2.tar.gz (288kB)",
> "    Complete output from command python setup.py egg_info:",
> "    Traceback (most recent call last):",
> "      File \"<string>\", line 1, in <module>",
> "      File \"/tmp/pip-build-6r_l0dhw/django-tenant-schemas/setup.py\", line 29, in <module>",
> "        long_description=open('README.rst').read() if exists(\"README.rst\") else \"\",",
> "      File \"/home/vagrant/ve/lib/python3.4/encodings/ascii.py\", line 26, in decode",
> "        return codecs.ascii_decode(input, self.errors)[0]",
> "    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 393: ordinal not in range(128)",
> "    ",
> "    ----------------------------------------"],
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bernardopires/django-tenant-schemas/issues/351#issuecomment-227399962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJOhDf-z9_nEzUj79AEssyRkkPiMBFRaks5qN7tSgaJpZM4Iz-QB>
> .
>


-- 
Cordialement,

Maxime Junique

Etudiant DUT INFO (Aix-En-Provence)

Webdesigner & Intégrateur HTML5/CSS3

Site : http://lavitrine-websites.fr/

**Comment by opb** [comment]
Thanks for the response. This is vanilla Ubuntu 14.04, so I'm surprised that it's not working by default, but I'll certainly dig a bit further.

thanks

**Comment by oplahcinski** [comment]
In case anyone else looks for this error message, hopefully this helps.

We just had a new ubuntu 14.04 vagrant box do this error message to us. I read [darkicex3's link](https://perlgeek.de/en/article/set-up-a-clean-utf8-environment) and  added 

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8

to .bashrc template and it installed the already downloaded `django-tenant-schemas==1.6.2 ` without issue.
