### ISSUE TITLE
Document utils.py module

### ISSUE THREAD

**Issue by filipeximenes** [bernardopires/django-tenant-schemas#355]
I may be missing on something here but it seems that the `utils.py` module is not documented. There are some interesting functions there that look like could be useful to developers.

e.g.: #322

**Comment by bernardopires** [comment]
Hi Filipe, do you want to send a patch adding the documentation? Thanks!

**Comment by bartmika** [comment]
+1

**Comment by rodolfomartinez** [comment]
+1

**Comment by filipeximenes** [comment]
This is done here: https://django-tenant-schemas.readthedocs.io/en/latest/use.html#utils
Closing this issue.
