### ISSUE TITLE
django.core.context_processors.request is deprecated

### ISSUE THREAD

**Issue by Arken94** [bernardopires/django-tenant-schemas#367]
The installation guide instructs the reader to make sure that 'django.core.context_processors.request' is in the TEMPLATE_CONTEXT_PROCESSORS in settings.py. However according to Django==1.9 docs it states 

> Furthermore you should replace django.core.context_processors with django.template.context_processors in the names of context processors.

So just a heads up. Great app so far either way. Many thanks.

**Comment by goodtune** [comment]
Thanks @Arken94 would you like to submit a pull request that corrects the documentation?

Keep in mind that we're attempting to support Django>=1.8 (LTS).

**Comment by bernardopires** [comment]
Thank you for spotting this!
