### ISSUE TITLE
Why is django.contrib.contenttypes in the tenant apps?

### ISSUE THREAD

**Issue by 3811** [bernardopires/django-tenant-schemas#369]
Hi, could you please explain why it says that django.contrib.contenttypes must be in tenant app?

```
TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',

    # your tenant-specific apps
    'myapp.hotels',
    'myapp.houses',
)
```

**Comment by 3811** [comment]
There is also "def test_content_types_is_not_mandatory(self):" test in 

https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/tests/test_tenants.py

Which makes me think that "django.contrib.contenttypes" should not be in tenant apps.  Is this correct?

**Comment by bernardopires** [comment]
Thanks for finding this, it does not have to be in `TENANT_APPS`. Most likely I forgot to update the documentation!

**Comment by eriktelepovsky** [comment]
Hi. Actually, it is still in the [documentation](https://django-tenant-schemas.readthedocs.io/en/latest/install.html#configure-tenant-and-shared-applications), both in SHARED_APPS and TENANT_APPS. Can you tell the difference having it or not in the TENANT_APPS please? I am not sure if I understand it correctly. Thank you.
