### ISSUE TITLE
manytomany on Permissions for Tenant App / is the command migrate_schemas --shared useless?

### ISSUE THREAD

**Issue by ghost** [bernardopires/django-tenant-schemas#370]
I have a Student model class in App1 and App2.
App1 is public while App2 is in another schema created programmatically. (App1 is a Shared App, App2 is a Tenant App)
CustomPermissionsMixin is based on django PermissionsMixin.
CustomPermissionsMixin is defined in Shared App

```
@python_2_unicode_compatible
class CustomPermissionsMixin(models.Model):
    """
    A mixin class that adds the fields and methods necessary to support
    Django's Group and Permission model using the ModelBackend.
    """
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_(
            'Designates that this user has all permissions without '
            'explicitly assigning them.'
        ),
    )
    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_name="%(app_label)s_%(class)s_related",
        related_query_name="%(app_label)s_%(class)ss",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('student user permissions'),
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_name="%(app_label)s_%(class)s_related",
        related_query_name="%(app_label)s_%(class)ss",
    )

    class Meta:
        abstract = True
    ....
```

```
class Student(AbstractBaseUser, CustomPermissionsMixin):
    ...

```

I have custom model backend 

```
class CustomBackend(ModelBackend):
    ....
```

App2 student's schema/table will not be created until some point later in the program. 
Since App2 student has manytomany relation to Permissions, Permissions now has app1 relation and app2 relation. I think it's registered by ManyRelatedManager. (Permissions sees these two relations as public schema)

If I do student1_of_app1.user_permissions.all(), Django will iterate over the relations that Permissions has. Including the non existing App2 table. Thus it'll create django.db.utils.ProgrammingError: relation does not exist.  
However, sometimes there is no error because Django gets into app1 relation first, but sometimes Django gets into app2 relation, hence the error.

Any suggestion on how can I make it work?

**Comment by fazzzmZozo** [comment]
I found out that run_migrations inside migrate_schema.py doesn't actually distinguish makemigrations for shared_apps and tenants apps.

```
    def run_migrations(self, schema_name, included_apps):
        if int(self.options.get('verbosity', 1)) >= 1:
            self._notice("=== Running migrate for schema %s" % schema_name)
        connection.set_schema(schema_name)
        command = MigrateCommand()
        command.execute(*self.args, **self.options)
        connection.set_schema_to_public()
```

As you see, `included_apps` are from `self.run_migrations(self.schema_name, self.shared_apps)` in handle function. However, going to command.execute(*self.args, **self.options) and handle function inside django migrate.py we'll see that the `included_apps` earlier is useless as `targets`
are always from migration graph `targets = executor.loader.graph.leaf_nodes()` 
This one will go through all migrations in the project - including tenant_apps.

is the command migrate_schemas --shared useless? since it migrates my tenant_apps as well.
Or am I missing something?
```
 # If they supplied command line arguments, work out what they mean.
        target_app_labels_only = True
        if options['app_label'] and options['migration_name']:
            app_label, migration_name = options['app_label'], options['migration_name']
            if app_label not in executor.loader.migrated_apps:
                raise CommandError(
                    "App '%s' does not have migrations." % app_label
                )
            if migration_name == "zero":
                targets = [(app_label, None)]
            else:
                try:
                    migration = executor.loader.get_migration_by_prefix(app_label, migration_name)
                except AmbiguityError:
                    raise CommandError(
                        "More than one migration matches '%s' in app '%s'. "
                        "Please be more specific." %
                        (migration_name, app_label)
                    )
                except KeyError:
                    raise CommandError("Cannot find a migration matching '%s' from app '%s'." % (
                        migration_name, app_label))
                targets = [(app_label, migration.name)]
            target_app_labels_only = False
        elif options['app_label']:
            app_label = options['app_label']
            if app_label not in executor.loader.migrated_apps:
                raise CommandError(
                    "App '%s' does not have migrations." % app_label
                )
            targets = [key for key in executor.loader.graph.leaf_nodes() if key[0] == app_label]
        else:
            targets = executor.loader.graph.leaf_nodes()

```

**Comment by fazzzmZozo** [comment]
I noticed django_content_types registers all apps from INSTALLED_APPS. Therefore it'll also register their permissions in public auth_permissions . Hence, the relation doesn't exist since the app2 is in its own schema. How can I not include tenant apps in django_content_type and auth_permissions? Is it intended by design?
