### ISSUE TITLE
Any way to treat base domain (example.com) as another tenant

### ISSUE THREAD

**Issue by SudShekhar** [bernardopires/django-tenant-schemas#375]
First of all, amazing app! Thanks a ton for having created this.

I am trying to create a multi-tenant website where the base domain is run by us and subdomains can be let out to other organizations (eg: `medium.com` vs `abc.medium.com`). 

Is there any way to make the base domain itself correspond to a tenant?

**Comment by bernardopires** [comment]
I don't understand what you mean. Do you want `medium.com` and `abc.medium.com` to be the same tenant or not? From what I understood you want `*.medium.com` to be one tenant and `*.example.com` to be another tenant, is that correct? All you have to change is the logic inside the `middleware.py`

**Comment by SudShekhar** [comment]
I basically want the following scenario (am using medium as the example here):

- `medium.com`  : site run by us, users register, read stuff 
- `abc.medium.com`/`xyz.medium.com`/any subdomain of our domain : site run by other company, users can register here too (the account is the same across the parent and all such tenants/subdomains), read stuff specific to that company.

When i first ran the migrations, all `shared` classes were created inside the `public` schema. then for each tenant the specific `schemas` are generated. This allows me to provide for all logins/readings across `subdomain.mydomain.com`.

But can I also treat the base domain itself as another tenant? Generate schema for that? What should be the `domain_url` for that?

**Comment by bernardopires** [comment]
There's nothing special about your setup and it doesn't require any modification to the code. From your description you want shared authentification, so you need `medium.com` to be your `public` schema. That's all.

**Comment by bernardopires** [comment]
Closing this for now, feel free to reopen!
