### ISSUE TITLE
Deleting a TenantMixin object doesn't remove schema in DB

### ISSUE THREAD

**Issue by Arken94** [bernardopires/django-tenant-schemas#378]
It seems as though if you create an object that inherits from `tenant_schemas.models.TenantMixin` it will create the proper schema in the DB, however if you delete the object it doesn't actually remove the schema. I feel like this is some what analogous to a "memory leak", if you will. Was this intended by design?

**Comment by Arken94** [comment]
Lack of reading the code on my part. Sorry.

**Comment by Arken94** [comment]
After reading the docs and finding auto_drop_schema, I tried setting that to True, however it still does not drop the schema

**Comment by bernardopires** [comment]
I can't reproduce it and have added a new test for this case.
