### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by filipeximenes** [bernardopires/django-tenant-schemas#379]
Using the `TenantTestCase` makes the tests very slow. Is there some way to speed things up? I'm taking 3.5 minutes to run a test suit of 111 tests, which is pretty high.

**Comment by john2x** [comment]
Removing the `cursor.execute('DROP SCHEMA test CASCADE')` line in the `tearDownClass` sped up or tests ~4x.

**Comment by filipeximenes** [comment]
Simply removing the mentioned line breaks the tests for me. But this works:

```
@classmethod
    def setUpClass(cls):
        cls.sync_shared()
        tenant_domain = 'tenant.test.com'

        TenantModel = get_tenant_model()

        try:
            cls.tenant = TenantModel.objects.get(domain_url=tenant_domain, schema_name='test')
        except:
            cls.tenant = TenantModel(domain_url=tenant_domain, schema_name='test')
            cls.tenant.save(verbosity=0)

        connection.set_tenant(cls.tenant)

    @classmethod
    def tearDownClass(cls):
        connection.set_schema_to_public()
```

It also works when running tests with `--parallel`  and `--keepdb`

**Comment by bernardopires** [comment]
@filipeximenes well yes, but now you're keeping state between your tests.

**Comment by filipeximenes** [comment]
@bernardopires Yes, aware of this. In my application this is not a problem and it's worth to do it given how much faster it is. Maybe we can add this as a functionality. We can have a settings variable to allow people to explicitly set tests to run without recreating the tenant. 
Another option is to just mention how to do this in docs. I'm sure there are more people that would be interested in this.

**Comment by bernardopires** [comment]
@filipeximenes Sure, you could create a new class `FastTenantTestCase`   and make it explicit in the comments that the state is shared between the test cases. Feel free to send a pull request and please add docs as well. Thanks! :+1:

**Comment by bernardopires** [comment]
Closing this for now, feel free to reopen!
