### ISSUE TITLE
Configuration option for default tenant?

### ISSUE THREAD

**Issue by UnrealAkama** [bernardopires/django-tenant-schemas#383]
This is something that I have an issue with that I'm guessing other people do as well. One thing I would like to be able to do is set a default tenant. For instance, if you request a hostname that isn't associated with a tenant or you access the the site using an IP directly, the tenant-schemas would just choose this default tenant for that request. 

The main purpose for is to enable the software to work better with load balancing health checks. Generally these applications ( Elastic Beanstalk is the case I'm using ) query the backend web app server using the ip address of the  server. This would enable you to enable HTTP health checks rather than just TCP health checks. 

I'm willing to write this feature as it doesn't seem complicated but what I'm asking is would other people be interested in this feature or how are other people handling health checks when using this extension.

**Comment by bernardopires** [comment]
So what does an HTTP health check consist of? Why does it check URLs that do not exist? A 404 is an unhealthy check?

**Comment by UnrealAkama** [comment]
A health check is a when the load balancer requests a URL to confirm that the web server is up and running correctly. Generally these are only considered valid if they return a 200 response code. One of the issues is that the load balancer is requesting with the IP address of the web server rather than a hostname which causes the application to return a 404. 

This is the example that I'm using but this would also fix other load balancers. 
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html

**Comment by bernardopires** [comment]
You could just add another tenant pointing to public with the ip address instead of the hostname. That should fix your problem.

**Comment by UnrealAkama** [comment]
That's a possibility and will work for some LB setups but it's not always guaranteed in a LB environment. I'll go ahead in the next couple of the days to write a quick extension that will allow people to setup a default site for unknown host names/ip addresses.
