### ISSUE TITLE
Problem with tutorial

### ISSUE THREAD

**Issue by anyeone** [bernardopires/django-tenant-schemas#395]
Greetings, 

I downloaded the project and updated the settings module to point to my database and attempted to run the project per the instructions but I get an error:

ValueError: Unable to configure filter 'tenant_context': Cannot resolve 'tenant_schemas.log.TenantContextFilter': No module named tenant_schemas

I also loaded into pycharm and tried running from there, but if I put the project root above the tenant_context app, the settings file is never found, but if I put the project root on examples where it can find the tutorial project's settings, then it can't resolve any references to tenant_context.

Please advise, thanks!

**Comment by anyeone** [comment]
It looks like there were some broken import references in the project.  I changed the way they were imported and now it runs.  The lines that were off were in the tenant_schemas.postgresql_backround folder primarily, but I used PyCharm's intellisense to correct the import statements.

**Comment by bernardopires** [comment]
Please do send a pull request with your fixes! Thanks!

**Comment by dparizek** [comment]
I want to write a tutorial to take a total newbie through installation and use of the example project.

The current documentation mentions "follow the tutorial" but I don't see an actual tutorial.  Does one exist that I am not seeing?  or should I create it and do a PR?
