### ISSUE TITLE
help me, about test

### ISSUE THREAD

**Issue by eileen-chen** [bernardopires/django-tenant-schemas#408]
Step 1: download django-tenant-schemas project
Step 2: go to dts_test_project folder, and run python manage.py migrate_schemas --shared
Step 3: run python test tenant_schemas.tests

error: 

Creating test database for alias 'default'...
E
======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/Users/XXX/.pyenv/versions/3.5.1/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/XXX/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tenant_schemas/tests/__init__.py", line 1, in <module>
    from test_routes import *
ImportError: No module named 'test_routes'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Destroying test database for alias 'default'...

How can I test the success?

**Comment by goodtune** [comment]
You can use `tox` to handle all the test suite setup. Just make sure you've done a `pip install --user tox` (outside of a virtualenv) and then from the project root, simply run `tox`.

If you still want to do it manually, read through [tox.ini](https://github.com/bernardopires/django-tenant-schemas/blob/master/tox.ini) to deduce what is expected for a successful test run.

More information on `tox` is available at https://tox.readthedocs.io/

**Comment by eileen-chen** [comment]
@goodtune thank you
