### ISSUE TITLE
Lengthly migrations

### ISSUE THREAD

**Issue by KarlSayle** [bernardopires/django-tenant-schemas#409]
Evening,

Just wondering if anyone else has had a similar issue. I have a system which has an ever growing migrations list which is caused fresh migrations/new user setups to have to wait around 40 seconds for the database to build which is throwing some timeout errors.

I think I will have to squash the migrations, however i just wanted to get any feedback before hand.

Thanks in advance.

**Comment by goodtune** [comment]
I think I actually deferred all my tenant setup to a celery task as I
didn't want the view blocking at all.

It may be overkill if you don't already use asynchronous workers in your
project, though.

**Comment by objectizer** [comment]
i did the same as @goodtune , i use djang-celery-with-redis, when creating a new tenant, i do that within a celery task that run in the background.

**Comment by KarlSayle** [comment]
Thanks for the comments. Ill look into Celery.

**Comment by erichurkman** [comment]
You can also pre-generate X new tenants and only "claim" them when a user signs up.

**Comment by bernardopires** [comment]
This should be fixed now as we have parallel migrations.
