### ISSUE TITLE
New version in PyPi

### ISSUE THREAD

**Issue by marcrosis** [bernardopires/django-tenant-schemas#410]
Are there any plans to upload a new version of this to PyPi ? Are there any issues that need to be fixed in order to reach the next milestone?

**Comment by goodtune** [comment]
Try as I might I cannot find any logs about the deployment on Travis. I've used exactly the same configuration in goodtune/vitriolic@7df3e927 and that worked fine - https://pypi.python.org/pypi/vitriolic/1.0.1

I just tried with 73a0495 but it doesn't appear that has worked either, unless it is queued somewhere?

@bernardopires if you want to extend my abilities to package maintainer on pypi, I can look at this further and also release manually if automation continues to fail us.

**Comment by MounirMesselmeni** [comment]
Hi,

Still no new version on pypi, I think the one fixing the test error with Postgresql 9.6 is important.

Thanks

**Comment by goodtune** [comment]
Found the deployment logs while reviewing fix of #414 ... see https://travis-ci.org/bernardopires/django-tenant-schemas/jobs/184768872#L457

@bernardopires it seems that the credentials are not being accepted? I'm afraid you're the only person who will be able to resolve this.

**Comment by AlexvEck** [comment]
@bernardopires Could you take a look at this? PyPi is 2 version behind now...

**Comment by goodtune** [comment]
I think we can safely close this now, I just pushed a new tag and before I'd even had a chance to run `python setup.py sdist upload` the release had been dutifully uploaded by Travis.
