### ISSUE TITLE
Problem with django.contrib.contenttypes

### ISSUE THREAD

**Issue by destin** [bernardopires/django-tenant-schemas#412]
Thanks for this great application, I am using it quite extensively.

However, recently I came across strange issue during migration.

My setup includes django.contrib.auth as SHARED_APPS and django.contrib.contenttypes in both SHARED_APPS and TENANT_APPS. 

After adding https://github.com/jazzband/django-constance (introduces new model classes) as SHARED_APP I get for one of tenants the following problem:

psycopg2.IntegrityError: insert or update on table "auth_permission" violates foreign key constraint "auth_content_type_id_320fdf2833dd9ac3_fk_django_content_type_id"
DETAIL:  Key (content_type_id)=(65) is not present in table "django_content_type".

Looks like migration failed for this tenant because migration mechanism tried to add new entries to public.auth_permission that reference `<tenant>.django_content_type`.

Therefore I have 2 questions:

1. For each tenant migrations from all apps are executed, even those from SHARED_APPS. From what I can see https://github.com/bernardopires/django-tenant-schemas/blob/7d4428cc7745d53f24876e5deb9a42d8cec41771/tenant_schemas/management/commands/migrate_schemas.py#L54 included_apps parameter is ignored. What is the reason for this?
2. Why django.contrib.contenttypes is suggested to be part of TENANT_APPS? Why all content types cannot be defined in shared schema?

**Comment by 3811** [comment]
Take a look at this  #369

**Comment by destin** [comment]
Thanks @3811. I have no idea how could I have missed that.

Although I did not get answer to 1. I close the ticket as I now know how to proceed.

**Comment by smbkzt** [comment]
> Thanks @3811. I have no idea how could I have missed that.
> 
> Although I did not get answer to 1. I close the ticket as I now know how to proceed.

Wouldn't you mind sharing the solution to this problem, please?
