### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by nikhiln** [bernardopires/django-tenant-schemas#417]
My tests are running very slow even though I am using `FastTenantTestCase`. There are around 30 unit tests. I have extended the `FastTenantTestCase` and created new base class (as described below). And all the unit test cases are extending this base class. As per my understanding `FastTenantTestCase` is much more faster compared to `TenantTestCase`, but it's till taking more than 10 mins to run all. Can someone please provide some direction to make it more faster or point out if anything is wrong with configuration? The code and config is described below:

```
class BaseTestCase(FastTenantTestCase):
    def setUp(self):
        """
        Returns: The tenant client
        """
        self._client = TenantClient(self.tenant)
        self._extra_headers = {'content_type': 'application/json'}

        # Create User object
        self._u1 = User(username='admin', email='test@localhost.com')
        self._PASS = 'admin'
        self._u1.set_password(self._PASS)
        self._u1.save()
```

**Installed apps setting:**

```
SHARED_APPS = (
    'tenant_schemas',  # mandatory
    'web.users.apps.UsersConfig',  # this must be first - using in audit trail - custom user app
    'django.contrib.auth',

    # Default Django apps:
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Useful template tags:
    'django.contrib.humanize',

    # Admin
    'django.contrib.admin',

    # Third party
    'crispy_forms',  # Form layouts

    # api
    'rest_framework',
    'rest_auth',
    'rest_auth.registration',

    # cors
    'corsheaders',

    # mailing, sms, push notifications
    'dbmail',

    # tagging
    'taggit',

    # Custom Apps
)

TENANT_APPS = (
    'web.users.apps.UsersConfig',  # this must be first - custom user app
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.postgres',
    # Admin
    'django.contrib.admin',

    # Third party
    'allauth',  # registration
    'allauth.account',  # registration
    'allauth.socialaccount',  # registration
    'invitations',  # invitations
    'django_countries',  # utility
    'djmoney',  # utility
    'phonenumber_field',  # phone number
    'permission',  # permission
    'notifications',  # notifications

    # api
    'rest_framework',
    'rest_auth',
    'rest_auth.registration',

    # cors
    'corsheaders',

    # mailing, sms, push notifications
    'dbmail',

    # tagging
    'taggit',

    # Custom Apps
)

```

**Comment by AlexvEck** [comment]
Hi, 

First off make sure you provide a way to clean the DB because FastTenantTestCase does not clean the DB between tests. From the docs;

> The gain in speed is noticeable but be aware that by using this you will be perpetrating state between your test cases, please make sure your they wont be affected by this.

You could use;
`
    @classmethod
    def tearDownClass(cls):
        super(DjangoFastTenantTestCase, cls).tearDownClass()

        cursor = connection.cursor()
        cursor.execute("""
            SELECT 'TRUNCATE ' || table_name || ';'
            FROM information_schema.tables
            WHERE table_schema='test';
        """)
`

To clean after every test has run, or on setUpClass to clean before them. Django rolls back the db transactions after each test has run.

Secondly, Can you try to run `python manage.py test -v 2` and see if you're migrations are just taking a long time? [If migrations really are the problem you can try squashing them.](https://docs.djangoproject.com/en/1.10/topics/migrations/#migration-squashing) or you can add [django-test-without-migrations](https://pypi.python.org/pypi/django-test-without-migrations/) and run your tests with the -n or --no-migrations flag.

Let me know if this gives you a nudge in the right direction.

**Comment by nikhiln** [comment]
@AlexvEck Thank you for hint. I tried your suggested way, but it didn't improve a lot. I have already tried to check if migrations are causing the issue with `test -v 3` but actually migrations are only taking around a min only. Any other thoughts?

**Comment by AlexvEck** [comment]
@nikhiln You are running tests concurrently? That can most definitely slow down your tests, since each tenant test case also accesses the public schema to connect itself to the right database.

Could you post the output of `test -v 2` or `test -v 3`?

**Comment by nikhiln** [comment]
@AlexvEck Please check  attached. Thank you for you help.

[test.txt](https://github.com/bernardopires/django-tenant-schemas/files/678721/test.txt)

**Comment by AlexvEck** [comment]
@nikhiln Hi. Thanks for the output. Setting up your test and running the initial migrations seems fine.

However I have never seen the output of Case 1:... Case 2:... before. What testing framework are you using? also, it seems that one of your tests creates a new tenant, from the output in the middle of a test. Are you testing if django-tenant-schemas creates a tenant? 

If you want I'll take a look at your code, is it on GH?

**Comment by nikhiln** [comment]
@AlexvEck Thank you for your help. The code is not available on github as it's including our proprietary code. I can do screen share if that works for you or let me see if I can share the git repo.

**Comment by nikhiln** [comment]
@AlexvEck I dig into the issue further. I refactored my test cases and now it's taking ~5 mins. After further investigation I found that the migrations are taking most of time. Any suggestions to improve that?

**Comment by AlexvEck** [comment]
As stated by the docs the only way to mitigate the migration slowness is to
use the FastTenantTestCase and clean it in between runs with the example
provided above.

Hope it helps!

**Comment by bernardopires** [comment]
Thanks for all the help here @AlexvEck!
