### ISSUE TITLE
django_extensions reset_db command fails

### ISSUE THREAD

**Issue by jacopsd** [bernardopires/django-tenant-schemas#419]
django 1.8.16, django-tenant-schemas 1.6.4, django-extensions 1.7.4

Need to reset the database (remove data, keep schema), so wanted to use the django-extensions "reset_db" command, but it fails as it doesn't know the postgresql_backend engine used by django-tenant-schemas:
```

  $ python manage.py reset_db
  You have requested a database reset.
  This will IRREVERSIBLY DESTROY
  ALL data in the database "swingit".
  Are you sure you want to do this?
  Type 'yes' to continue, or 'no' to cancel: yes
  CommandError: Unknown database engine postgresql_backend
  $ 
```

Any work around to reset the DB using django-tenant-schemas?

**Comment by AlexvEck** [comment]
I take it you want to truncate all schemas, including the public schema? You will lose all of your clients as well, as well as the public client.

In a django shell (`python manage.py shell`) do:

```
from django.db import connection
cursor = connection.cursor()
cursor.execute("""
    SELECT 'TRUNCATE ' || table_name || ';'
    FROM information_schema.tables;
""")
```

This will go through each schema and truncate every single table. You will also lose the CLIENT_MODEL table, which means you'll have schemas that aren't registered in the public schema and can't be accessed unless you add them again. Or you can exclude that table from the query; `WHERE NOT (table_schema='public' and table_name='CLIENT_MODEL_TABLE_NAME')`

Hope this helps!

**Comment by devxpy** [comment]
thanks!
