### ISSUE TITLE
Using django app config will make a SystemCheckError

### ISSUE THREAD

**Issue by MounirMesselmeni** [bernardopires/django-tenant-schemas#423]
```python
    # Take the app_configs and turn them into *old style* application names.
    # This is what we expect in the SHARED_APPS and TENANT_APPS settings.
    INSTALLED_APPS = [
        config.name
        for config in app_configs
    ]
```

This part of code inside the checking code, make it not possible to use AppConfigs, I don't see the why it's this way as mentioned in the comment. Any one have an idea about this?

**Comment by AlexvEck** [comment]
What version of Django did you test this on?

This explicitly allows working with AppConfigs, make sure to have a name attribute in your app_config.

Can you provide some more background information?

**Comment by MounirMesselmeni** [comment]
I'm using Django 1.10 and the latest release of django-tenant-schemas, I've the name attribute in the app config also.

```python
class MyAppConfig(AppConfig):
    name = 'myapps'
```

in the settings.py:

```python
SHARED_APPS = [
    ...,
    'myapp.apps.MyAppConfig',
]

TENANT_APPS = [
    'django.contrib.contenttypes',
    'reversion',
    'django_comments',
    ...,
] 
INSTALLED_APPS = SHARED_APPS + [x for x in TENANT_APPS if x not in SHARED_APPS]
```

Then when I run the server I get this check error:
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: You have SHARED_APPS that are not in INSTALLED_APPS
	HINT: ['myapp.apps.MyAppConfig']

**Comment by AlexvEck** [comment]
From what I can read in the source django-tenant-schemas will respect the AppConfig name or the long format.

So you can either use;
```
SHARED_APPS = [
    ...,
    'myapp.apps.myapps',
]
```
or
```
SHARED_APPS = [
    ...,
    'myapps',
]
```

Am I correct?

**Comment by goodtune** [comment]
I added the AppConfig system check; my interpretation of the `SHARED_APPS` and `TENANT_APPS` settings is that they take dotted module paths and does not deal with paths to an AppConfig class.

**Comment by MounirMesselmeni** [comment]
The comparaison inside `tenant_schemas/apps.py` is not respecting the long name, `INSTALLED_APPS` will contains only the name from AppConfig (Short name) and then the SHARED_APPS will contains the path to the AppConfig (the long name) and that's the issue here 
(line 23)
```python
# Take the app_configs and turn them into *old style* application names.
    # This is what we expect in the SHARED_APPS and TENANT_APPS settings.
    INSTALLED_APPS = [
        config.name
        for config in app_configs
    ]
```


(line 82)
```python
    if not set(settings.SHARED_APPS).issubset(INSTALLED_APPS):
        delta = set(settings.SHARED_APPS).difference(INSTALLED_APPS)
        errors.append(
            Error("You have SHARED_APPS that are not in INSTALLED_APPS",
                  hint=[a for a in settings.SHARED_APPS if a in delta]))
```

**Comment by goodtune** [comment]
This isn't a bug; `INSTALLED_APPS` is where you should have `'myapp.apps.MyAppConfig'` and in `SHARED_APPS` you should have `'myapp'`.

**Comment by goodtune** [comment]
The documentation at http://django-tenant-schemas.readthedocs.io/en/latest/install.html#configure-tenant-and-shared-applications could possibly do with some improvement, nowhere does it cite an AppConfig example.

**Comment by MounirMesselmeni** [comment]
I got it, but it will not be clean to redefine the app in two places, one in `SHARED_APPS` with the old syntax and in `INSTALLED_APPS` with the new syntax.
This will prevent defining an app in a single places and build the `INSTALLED_APPS` with list concatenation like the example I gave.

**Comment by goodtune** [comment]
I think that `INSTALLED_APPS`, `SHARED_APPS`, and `TENANT_APPS` should be curated manually; conveniences aside, I've already encountered occasions when the order in `INSTALLED_APPS` matters and simple concatenation isn't suitable... that is why I made the example in the documentation explicit.

**Comment by MounirMesselmeni** [comment]
Okay, it's clear now, thanks for your time and your explanations.
