### ISSUE TITLE
TenantTestCase - DROP SCHEMA fails when auto_drop_schema is True

### ISSUE THREAD

**Issue by AlexvEck** [bernardopires/django-tenant-schemas#424]
As the title says;

When the Tenant model has `auto_drop_schema = True` the TenantTestCase will always fail because the preceding line `cls.tenant.delete()` already deletes the schema.

We could rewrite it to; `DROP SCHEMA IF EXISTS test CASCADE` and it would be fine.

Any thoughts?

**Comment by bernardopires** [comment]
Thanks for reporting the issue and for writing the fix @AlexvEck.
