### ISSUE TITLE
./manage.py migrate_schemas for all schemas except "public"

### ISSUE THREAD

**Issue by Arken94** [bernardopires/django-tenant-schemas#428]
Anyway to migrate all schemas except the shared one?

**Comment by AlexvEck** [comment]
If you look at the help of the migrate_schemas command (`python manage.py migrate_schemas --help`) you'll find;
```
  --tenant              Tells Django to populate only tenant applications.
  --shared              Tells Django to populate only shared applications.
```

So, you can accomplish migrating only tenants by using:
```
python manage.py migrate_schemas --tenant
```

**Comment by Arken94** [comment]
Thanks!

**Comment by dhirajshinde121083** [comment]
like this can i create table tenantwise e.g i have tenant say A,B,C 
A have table x,y,z
B have table p,q,r,x
C have table l,m,n,p,z
can we achieve this using django_tenant_schemas ?
