### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by chrispbailey** [bernardopires/django-tenant-schemas#429]
Looking at upgrading django-tenant-schemas but can't find a changelog anywhere.

**Comment by goodtune** [comment]
You could use GitHub's compare feature?

https://github.com/bernardopires/django-tenant-schemas/compare/v1.6.4...v1.6.10

Adjust the versions as required.

**Comment by chrispbailey** [comment]
May I suggest that it would be good idea for any open source project to have an easily viewable change log, rather then your solution which I then have to follow all the (none automatically linked) issues numbers you find out what really changed

**Comment by bernardopires** [comment]
I do agree they make sense, however we are not able to invest enough time in this project to create changelogs. A lot of the development in this project already happens through members generously contributing their time to write pull requests. I would not like to force them to write changelogs.
