### ISSUE TITLE
New architecture does not seem to allow centralized django.contrib.auth

### ISSUE THREAD

**Issue by surfer26th** [bernardopires/django-tenant-schemas#43]
It's been awhile since I inspected tenant_schemas. I've been using a branch successfully in my SaaS. I wanted to check out the latest commit. In doing so, however, the latest software seems to not work with my requirements.

I require that django.contrib.auth exists in public, since I want centralized authorization and billing (my stripe-based billing app needs to join in with the auth_user table). However, it seems that the latest tenant_schema code requires that auth also be placed in TENANT_APPS (in addition to optionally in SHARED_APPS). Otherwise, I get a DB error when doing sync_schemas. However, when I do that and successfully do a sync_schemas, my users (for which there exists an auth table in public) are not authorized to login into a tenant. I suppose I would need to somehow synchronize the user in each tenant with auth_user in public. But that would be too unwieldy.

I would like to use the latest commit. With my current branch of tenant_schemas (forked 9 months ago), whenever I do a syncdb, I need to delete tables in public that should only be in each tenant. Your latest commit seems to have a solution for that using sync_db. 

Any thoughts?

**Comment by tpyo** [comment]
@bernardopires Thanks for this.  The TenantSyncRouter probably needs allow_migrate(), I saw some warnings about this when migrating to 1.7.

From the 1.7 release notes:
```The allow_syncdb method on database routers is now called allow_migrate, but still performs the same function. Routers with allow_syncdb methods will still work, but that method name is deprecated and you should change it as soon as possible (nothing more than renaming is required).```

**Comment by bernardopires** [comment]
I guess we'll need to keep both because of 1.6, thanks for the heads up tpyo! Do you want to send a pull request that adds allow_migrate() performing exactly like allow_syncdb()?

**Comment by tpyo** [comment]
Happy to: #217

**Comment by surfer26th** [comment]
Bernardo - I forked your experimental branch (experimental db router) that you created in late 2013  ("fixed sync_schemas and migrate_schemas not taking arguments") and have been using it with Django 1.5.5 on my production server with success since. I have done quite a few migrations in development and in production successfully. As I am updating/upgrading my software, I hope to get back in sync with your master. Thank you for your continued work on this and specifically for closing this issue out!

Thanks to typo for the warning on Django 1.7 and migrations. I will not upgrade to Django 1.7, but hope to upgrade to 1.6.

**Comment by bernardopires** [comment]
Hi Ted @surfer26th, I'm now using the router in the master so you should have no problems upgrading! Let me know if you have any issues. Thanks for your continued suppport!
