### ISSUE TITLE
Overly restrictive django.conf.settings warning

### ISSUE THREAD

**Issue by chrispbailey** [bernardopires/django-tenant-schemas#430]
The following line requires `tenant_schemas` to be first in the `INSTALLED_APPS` list.

```
    if INSTALLED_APPS[0] != 'tenant_schemas':
        errors.append(
            Warning("You should put 'tenant_schemas' first in INSTALLED_APPS.",
                    obj="django.conf.settings",
                    hint="This is necessary to overwrite built-in django "
                         "management commands with their schema-aware "
                         "implementations."))
`````
However I think this is too broad a check as it makes it difficult for someone to override `django-tenant-schemas`'s management commands with their own (as we do in our project). I suggest instead checking that `tenant_schemas` is placed before any `django.*` apps which is what the warning message implies

**Comment by bernardopires** [comment]
Why is that a problem? Do you have another app that needs to be first?

**Comment by AlexvEck** [comment]
@chrispbailey @goodtune #433 has been merged, so this issue can be closed :)
