### ISSUE TITLE
Wrong checks with AppConfig

### ISSUE THREAD

**Issue by stephane** [bernardopires/django-tenant-schemas#437]
The SystemCheck fails on 'You have SHARED_APPS that are not in INSTALLED_APPS' and 'TENANT_APPS that are not in INSTALLED_APPS' but my apps are properly set up.

Does it work with AppConfig?
HINT: ['foo.bars.apps.CompaniesConfig']

**Comment by goodtune** [comment]
Can you please share the values of `SHARED_APPS`, `TENANT_APPS` and `INSTALLED_APPS`?

`SHARED_APPS` and `TENANT_APPS` cannot contain `AppConfig` references, only application names.

The system check turns `AppConfig` references in `INSTALLED_APPS` back into application names before comparison.

```python
# Take the app_configs and turn them into *old style* application names.
# This is what we expect in the SHARED_APPS and TENANT_APPS settings.
INSTALLED_APPS = [
    config.name
    for config in app_configs
]
```

**Comment by goodtune** [comment]
I don't think this is a bug, so I'm closing the issue.

If you disagree, re-open and provide information requested above.

**Comment by stephane** [comment]
It was an issue with the current limitation of the Tenant models.py in the project tree (the app must be in the root dir), may be I will take the time to provide a patch....
