### ISSUE TITLE
Schemas are not deleted when using queryset bulk delete method

### ISSUE THREAD

**Issue by izimobil** [bernardopires/django-tenant-schemas#446]
Hi, 
First, thanks to all contributors for this excellent app that solves a difficult problem.

When using django queryset `delete` method on tenants (for example when you delete tenants in the django admin) schemas are not dropped even if `auto_drop_schema` is set to `True`.

This is normal because django queryset `delete` doesn't call the models `delete` method.
I will make a pull request to workaround the issue.
Regards.

**Comment by izimobil** [comment]
https://github.com/bernardopires/django-tenant-schemas/pull/447

**Comment by bernardopires** [comment]
This was merged in #447
