### ISSUE TITLE
Question about schema table population

### ISSUE THREAD

**Issue by lgfausak** [bernardopires/django-tenant-schemas#45]
Hi,

I haven't installed the multi-tenant package yet.  I think perhaps it doesn't meet my requirements.  If I understand correctly, the TENANT_APPS' tables are created in each of the tenant schemas.  So, if I want to run a query that spans all of the data in all the schemas I would have to do a union, correct?

I had an idea.  One thing you can do in postgres is inherit a table.  So, for example, I can create my table in the public schema, then, when I want that same table for a tenant I could:

1) create the tenant schema.
2) create table tenant.mytable () inherits (public.mytable);

When the tenant table is separate, data inserted into that table cannot be accessed by another tenant.  However, all data entered in a tenant schemas can be selected in the central  'public.mytable' table.  Another neat side effect is when south updates the public table the tenant tables automatically. I tried this a bit, I am going to do some more work with this.  What do you think about this approach?

---greg

**Comment by fgmacedo** [comment]
Hi @lgfausak!

Did your changes are live elsewhere? I'm trying to integrate `django-tenant-schemas` into a project and looking for a solution to use inheritance on some models.

Thanks!
