### ISSUE TITLE
TENANT_CREATION_FAKES_MIGRATIONS doesnt do what it says

### ISSUE THREAD

**Issue by LegoStormtroopr** [bernardopires/django-tenant-schemas#458]
[The documentation says](http://django-tenant-schemas.readthedocs.io/en/latest/install.html#TENANT_CREATION_FAKES_MIGRATIONS):

> TENANT_CREATION_FAKES_MIGRATIONS
> Default:	'True'
> Sets if the models will be synced directly to the last version and all migration subsequently faked. Useful in the cases where migrations can not be faked and need to be ran individually. Be aware that setting this to False may significantly slow down the process of creating tenants.

But, this isn't true (at least for me) and a cursory search of the code base shows that `TENANT_CREATION_FAKES_MIGRATIONS` only shows up once - in the documentation.

Mandatory system detail:
```
Python 3
Django (1.10.6)
django-tenant-schemas (1.7.0)
psycopg2 (2.7.1)
```

**Comment by LegoStormtroopr** [comment]
And checking the whole history shows that feautre has *never* been there :/

**Comment by w0rp** [comment]
I am also interesting in seeing a solution for this. My team has been trying to combine pytest, django-tenant-schemas, and the `--nomigrations` flag for the django plugin for pytest, possibly in combination with `--reuse-db`, and we've had a lot of trouble getting everything to work. It would be nice to see some `syncdb` style support for creating databases with django-tenant-schemas.

**Comment by craigloftus** [comment]
@LegoStormtroopr Not sure how you checked the history, but it **was** there: https://github.com/bernardopires/django-tenant-schemas/commit/4330f75b20ff60c765e418bb825285fabf650eba

However, it was using a South specific option, and it seems with the Django 1.7 changes the feature was version gated and then eventually dropped apart from in the docs.

**Comment by craigloftus** [comment]
I think if you can accept `Client.auto_create_schema=False` you should be able to get somewhere using the [MIGRATION_MODULES](https://docs.djangoproject.com/en/1.10/ref/settings/#migration-modules) setting with `None` values and `migrate_schemas -s <schema> --run-syncdb`.

It might be possible to add back support for the `TENANT_CREATION_FAKES_MIGRATIONS` flag following the approach I've suggested.

**Comment by w0rp** [comment]
I'll note, this issue may also be related to #469, where using `--reuse-db` and `--nomigrations` together fails.

**Comment by LegoStormtroopr** [comment]
@craigloftus thanks for the update, it was a headscratcher. Fortunately, I solved my issue. It turned out there was a conflict between tenanted migrations, signals, RunPython migrations and overly nested transactions.

I squashed some migrations and everything was fine.

Thanks for the library. I suppose the best fix is just removing that from the docs then?
