### ISSUE TITLE
django tenants schema doesn't seem to work on firefox

### ISSUE THREAD

**Issue by saneletm** [bernardopires/django-tenant-schemas#460]
When trying to access my app on firefox I don't get access. 

Server not found

Firefox can’t find the server at www.tenat.organization.org

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

This works on chrome

**Comment by stephane** [comment]
django-tenant-schemas is a server side solution so it can't be dependent on used browser.

**Comment by saneletm** [comment]
I guess that make sense. I will check why it doesn't work. can I leave this open in the mean time?

**Comment by stephane** [comment]
The issue don't provide a way to reproduce it so it's currently useless. I think it's better to close it.

**Comment by saneletm** [comment]
well, the step to reproduce is to setup tenants using this app, and checking if you can reach your tenants using firefox browser. But you have a good point in saying this is a server side add on. it should not affect which browser the the user uses (at least theoretically). I will close for now.
