### ISSUE TITLE
tenant are not accesible on organization domain

### ISSUE THREAD

**Issue by saneletm** [bernardopires/django-tenant-schemas#461]
if I set up tenants and then I try visiting tenant.hostname.organization.org, this does not work?
I am wondering if the tenants only work if you have something like, tenant.hostname.org, but fails on tenant.hostname.organization.org. 

Before setting up tenants, i could access my application at hostname.organization.org. I added a tenant "tenant" hopping to access it through tenant.hostname.organization.org, but I get  - 

This site can’t be reached

tenant.hostname.organization.org’s server DNS address could not be found.
Search Google for blahhh
ERR_NAME_NOT_RESOLVED

**Comment by stephane** [comment]
You must first resolve your DNS issue before reporting an issue (the app is just not reached)!

**Comment by saneletm** [comment]
I will investigate this further. I guess for me its confusing that before wiring tenants, I can get to hostname.organization.org, then wire in tenants, I can still get to hostname.organization.org, but not to **tenant**.hostname.organization.org. I will investigate further and update. can I leave this open in the meantime?

**Comment by stephane** [comment]
I think it would be easier for the maintainer if you close it until further investigation.

**Comment by saneletm** [comment]
sounds good. closing for now.

**Comment by saneletm** [comment]
this was dns settings. needed to add tenant.hostname.organization.org to hosts file.
