### ISSUE TITLE
Not working with DRF (Django Rest Framework)

### ISSUE THREAD

**Issue by JakeMana** [bernardopires/django-tenant-schemas#474]
When using a model in tenant app, DRF has a problem with relations. 
After executing a request, I get "relation "lists_measureunit" does not exist. LINE 1: ..."restored_at", "lists_measureunit"."deleted" FROM "lists_mea..."

When I use the same model with no changes in shared app, everything is ok.

**Comment by Viatrak** [comment]
django-tenant-schemas works alongside DRF.

Remember, the schema has to be set to the tenant's schema to access the models in that tenant. Typically this happens automatically when a request comes into tenant.mydomain.com, but if an attempt to access a tenant's models are done outside of that request/response cycle, the schema won't be set properly.

**Comment by JakeMana** [comment]
I got it, thanks :)
