### ISSUE TITLE
Compatibility with Django 1.11 LTS (Tutorial)

### ISSUE THREAD

**Issue by juanvmarquezl** [bernardopires/django-tenant-schemas#477]
I'am doing some tests to use django-tenant-schemas and I found several errors on tenant_tutorial settings,py file. 

I attach the updated setting.py file.
[settings.py.zip](https://github.com/bernardopires/django-tenant-schemas/files/962653/settings.py.zip)

**Comment by mechaxl** [comment]
Thanks for this. I also had to change line 158 to this in order to eliminate a warning about installed app order:

```python
from collections import OrderedDict
INSTALLED_APPS = list(OrderedDict.fromkeys(SHARED_APPS + TENANT_APPS))
```

**Comment by bernardopires** [comment]
Please send a pull request instead. Thanks!
