### ISSUE TITLE
NameError: global name 'MigrateCommand' is not defined

### ISSUE THREAD

**Issue by rosarior** [bernardopires/django-tenant-schemas#483]
Error line: https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/management/commands/migrate.py#L13

MigrateCommand is not imported or defined anywhere in the module.

**Comment by mikicz** [comment]
Fixed in 70fef87576ac997fdb4e1c265152cc8f2929141a, @bernardopires you can close this now
