### ISSUE TITLE
Multilevel tenancy

### ISSUE THREAD

**Issue by geekashu** [bernardopires/django-tenant-schemas#487]
I have a use case where I need to implement nested tenancy.

For ex.
```
example.com
tenant1.example.com
subtenant1.tenant1.example.com
```

Would appreciate if you could help me understand how using this package I can implement deep/multi level tenancy?

**Comment by goodtune** [comment]
You define your own tenant model, so you can have a "parent" foreign key that points to self to build a hierarchy of tenants. That won't enforce the DNS lineage, you will need to look after that if it's a hard requirement.

You may want to look at combining that with django-mptt if you need efficient tree traversal.
