### ISSUE TITLE
Schema migrations error

### ISSUE THREAD

**Issue by sergefrvg** [bernardopires/django-tenant-schemas#490]
Hello!
This is a quick question. When I made my first public tenant and schema-migration everything went well. But when I tried to make the migrations for a different schema I got this error: `django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (relation "django_migrations" already exists)
`
I used the instructions in the docs ( [https://django-tenant-schemas.readthedocs.io/en/latest/use.html#creating-a-tenant](url)). 

What can be causing this error? Everything else was configured according to the docs and the public schema works. Even the new tenant works when accessing it through host.domain. It just does not make any migrations, therefore no new schema is created in the db.

I used `python manage.py shell` to create both tenants and `python manage.py migrate_schemas` for the migrations. 

Thanks a lot in advance!

**Comment by sergefrvg** [comment]
Ok, so apparently this has to do with the naming of the schemas, if you capitalize them then something happens that the new schema is never created. I guess this is more of a postgres thing that django-tenant-schemas. Thanks anyway. I'm going to close this now.

**Comment by manaladham** [comment]
Hello, I don't understand how you fixed this issue, could you please explain? Thanks.

**Comment by GeeWee** [comment]
I've had the same issue. When my schema_name was "TEST_TENANT" it did not work, but when it was "TESTTENANT" it did. Pretty strange.
