### ISSUE TITLE
Loading fixtures in both public and test schemas when running tests

### ISSUE THREAD

**Issue by jonperron** [bernardopires/django-tenant-schemas#506]
Using a similar stack to https://github.com/bernardopires/django-tenant-schemas/issues/398, I am trying to move tests written for a single tenant approach to a multi tenant approach (Django + Django REST Framework  + django-tenant-schemas). 

I am wondering how the fixtures are handled using the `FastTenantTestCase` and `rest_framework.test.APITestCase`. Indeed, it is loading all the fixtures in the `public` schema of the test DB but nothing is loaded in the `test` schema, thus leading all the tests to fail because nothing is present in the database. Did I miss something in the documentation or is it a missing feature ?

**Comment by tkowark** [comment]
I am running into a similar issue, and it seems that setUpClass is just overwritten and does not call TestCase.setUpClass. Unfortunately, this method is the one loading the fixtures. I've tested locally that entering TestCase.setUpClass() at the end of TenantTestCase.setUpClass or FastTenantSetUp, respectively. Here's a workaround:

**Comment by jonperron** [comment]
Thanks for your input @tkowark !

**Comment by MichaelAnckaert** [comment]
I just ran into this issue. When using the `TenantTestCase` fixtures defined in the test class aren't loaded. Getting into the code revealed that `TenantTestCase.setUpClass` didn't properly call the superclass constructor. 

A simple work around is adding the following code in your own test class:

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        super(TenantTestCase, cls).setUpClass()

@jonperron referenced the source file (https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/test/cases.py#L23) but there is no code that I see that touches on #339 ?

**Comment by jonperron** [comment]
Following your answer @MichaelAnckaert and thus @tkowark 's anwer, I still cannot get my tests working, but I managed to find out an alternative solution which improved (slightly) my output :
```

**Comment by icebrick** [comment]
I meet the same problem, here is what I do to meet my requirement:
```
class TenantFixtureTestCase(TenantTestCase):
 
    fixtures_public = None
    fixtures_tenant = None

    @classmethod
    def setUpClass(cls):
        # ---
        #
        super(TestCase, cls).setUpClass()
        cls.cls_atomics = cls._enter_atomics()

        # load fixtures_public to 'public' schema of database, now the schema of connection is 'puiblic'
        if cls.fixtures_public:
            for db_name in cls._databases_names(include_mirrors=False):
                try:
                    call_command('loaddata', *cls.fixtures_public, **{
                        'verbosity': 0,
                        'commit': False,
                        'database': db_name,
                    })
                except Exception:
                    cls._rollback_atomics(cls.cls_atomics)
                    raise
        # ---
        # call the origin method, for add tenant record to public
        super().setUpClass()

        # ---
        # load fixtures_tenant to 'test' schema, now the schema of connection is 'test'
        if cls.fixtures_tenant:
            for db_name in cls._databases_names(include_mirrors=False):
                try:
                    call_command('loaddata', *cls.fixtures_tenant, **{
                        'verbosity': 0,
                        'commit': False,
                        'database': db_name,
                    })
                except Exception:
                    cls._rollback_atomics(cls.cls_atomics)
                    raise

        try:
            cls.setUpTestData()
        except Exception:
            cls._rollback_atomics(cls.cls_atomics)
            raise
```
Hope it helps
