### ISSUE TITLE
Tenant schemas and Django Rest Framework testing (token auth)

### ISSUE THREAD

**Issue by AustinGomez** [bernardopires/django-tenant-schemas#508]
Hi there, I'm trying to test some of my code but I'm running into some issues. I'm using django-tenant-schemas along with Django rest framework and I'm trying to attach a user to the requests my TenantClient creates in my test setup.

I've tried:
client.login(...)
client.force_login(...)
etc.

Thanks in advance.

**Comment by BillBrower** [comment]
@AustinGomez how'd you end up fixing this?
