### ISSUE TITLE
Using django-tenant-schema and GeoDjango(Postgis) together.

### ISSUE THREAD

**Issue by shubhamagarwal003** [bernardopires/django-tenant-schemas#509]
I want to use django-tenant-schemas and [GeoDjango (PostGIS)](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/) in my Django project. I have a single default database. But both django-tenant-schemas and GeoDjango want me to set a custom Engine for the Database in the settings. django-tenant-schemas want it to be set to tenant_schemas.postgresql_backend while GeoDjango wants it to be set to django.contrib.gis.db.backends.postgis.Is there any workaround to this issue?

**Comment by Guest007** [comment]
More than one and half year ago :-) in #325

**Comment by shubhamagarwal003** [comment]
I did it more simply by changing the ORIGINAL_BACKEND in tenant_schame.postgresql_backend.base
I changed it to 
`ORIGINAL_BACKEND = getattr(settings, 'ORIGINAL_BACKEND', 'django.contrib.gis.db.backends.postgis')`

from 

`ORIGINAL_BACKEND = getattr(settings, 'ORIGINAL_BACKEND', 'django.db.backends.postgresql_psycopg2')
`

**Comment by dhirajshinde121083** [comment]
Thanks you very much shubham
