### ISSUE TITLE
Compatibility and updates

### ISSUE THREAD

**Issue by JakeMana** [bernardopires/django-tenant-schemas#510]
Hi, 
I'm just wondering whether its compatible with Django 1.11, Python 3.6 and PostgreSQL 10.1 or not. If not is there any plan for adding this compatibility? 
Thank you

**Comment by goodtune** [comment]
It may just work. We test against the currently supported releases of Django, as noted in the documentation. 

https://django-tenant-schemas.readthedocs.io/en/latest/use.html
