### ISSUE TITLE
About ImageField path

### ISSUE THREAD

**Issue by healz-lucifer** [bernardopires/django-tenant-schemas#512]
In My Tenant Model I added imagefields for tenant logo 
It uploaded fine to the path media that I assign in the settings.py.
let say 'D:\Media'

I noticed when I upload using tenant model they make a subfolder in my MEDIA_ROOT for each domain_url for the applications located (tenant or public)
But when showing the url from the imageField.
the domain_url was not included 
examples: media/clients/public/Lighthouse.jpg

instead of media/localhost/clients/public/Lighthouse.jpg

Is there anyway that the image url showing the right path?
and since this is on the public apps. I cannot use get_hosts, that will produce different result for each tenant. 

Any assistance would be of great help

**Comment by zapotocnylubos** [comment]
hi, this should by managed by reverse proxy (Nginx,..) that makes alias to media root by domain name.
[docs](http://django-tenant-schemas.readthedocs.io/en/latest/use.html#storage)

so in production this is solved, but what on local development with ./manage.py runserver? have you found solution? I have this problem too.

**Comment by mil-multi-it** [comment]
I also have this problem in development mode - any news on the topic?

**Comment by mezitax** [comment]
I also have this problem in development mode :/
