### ISSUE TITLE
Ability for custom FileSystemStorage without warnings

### ISSUE THREAD

**Issue by jeroenbrouwer** [bernardopires/django-tenant-schemas#518]
I have adjusted the `tenant_schemas.storage.TenantFileSystemStorage` to use `schema_name` instead of `domain_url` because we are not using the `domain_url`. It's a simple edit but gives the warning 

> (tenant_schemas.W003) Your default storage engine is not tenant aware.
> 	HINT: Set settings.DEFAULT_FILE_STORAGE to 'tenant_schemas.storage.TenantFileSystemStorage'

all the time. Could we have a way to prevent this warning from showing up or a better to check for the FileSystemStorage to be tenant aware?

**Comment by JRivasS** [comment]
This documentation on django-tenant...
https://django-tenant-schemas.readthedocs.io/en/latest/use.html#storage

in settings add line -> DEFAULT_FILE_STORAGE = 'tenant_schemas.storage.TenantFileSystemStorage'

**Comment by jeroenbrouwer** [comment]
Did you even read my issue...?

**Comment by mikicz** [comment]
The error will go away if your new storage class is a subclass of `TenantStorageMixin`. Yeah I know you're redefining the entire single method of that mixin but that's how that warning is set up...

**Comment by jeroenbrouwer** [comment]
That’s what I did. The problem with the warning is that it’s checked with isinstance() and not issubclass().
