### ISSUE TITLE
Question: What about the apps that are in both public and tenant apps?

### ISSUE THREAD

**Issue by devxpy** [bernardopires/django-tenant-schemas#527]
From what i understand, 

For `TENANT_APPS`  data is not to be shared with any of the other tenants

For `SHARED_APPS`, data is shared between tenants

Then what about apps that are specified in both the  `TENANT_APPS` and `SHARED_APPS` setting.

Like the ` 'django.contrib.contenttypes'` app, that is specified at both places in the example config

**Comment by JohnnyFang** [comment]
I'm not quite sure what you are asking, but I'm going to answer based on my own experience.
I'm going to use `'django.contrib.auth'` as an example. in my project I placed it in both, since I want to be able to have different users for my tenant schemas and my public one.

**Comment by devxpy** [comment]
Right, so users in the public schema will be separate than ones in each tenant's schema.

Got it thx
