### ISSUE TITLE
Any schedule for support MySQL?

### ISSUE THREAD

**Issue by Falldog** [bernardopires/django-tenant-schemas#537]
The tenant feature of the project is what I am looking for. But it’s only support PostgreSQL now. Any schedule for support MySQL? It should be only need to add database wrapper for different database right?

**Comment by goodtune** [comment]
No, MySQL does not have schema support.

**Comment by Falldog** [comment]
@goodtune 
I just realized what's different between database & schema, thanks for your answer.

My project is using MySQL as database, and we need to support multiple tenants by different domain & request, just like the `django-tenant-schemas`. I'm wondering that maybe MySQL is not a good choice for multiple tenants architecture. Could you tell more information about `schema` better than `database` design for multiple tenants. So I will think about it to change my database from MySQL to Postgrs. Thanks a lot
1. The ability to do cross-schema queries when needed 
2. The restricted user(tenant) can only be accessed by its self

**Comment by goodtune** [comment]
If you don't have a need for sharing data between tenants, then you could simply use the bog standard multiple database feature of Django.

When you construct your `QuerySet` use the `using` method the model `Manager` to make your choice. Here is a naive example.

```python
# settings.py

DATABASES = {
    'default': { ... },
    'tenant1': { ... },
    'tenant2': { ... },
}

# views.py

def foo(request):
    host = request.get_host()
    if host == "tenant1.example.com":
        using = "tenant1"
    elif host == "tenant2.example.com":
        using = "tenant2"
    else:
        using = "default"
    foo_list = Foo.objects.using(using)
    return TemplateResponse(request, 'foo.html', {'foo_list': foo_list})
```

The mode you won't be able to handle is if you have an application that shares data between tenants and some require tenant isolation. This can still be done with MySQL – but it will require more work.

**Comment by Falldog** [comment]
Thanks for your illustration, my project do not need to share data between tenants. I will keep going on the study on MySQL support our own multiple tenants mechanism. 

Thanks
