### ISSUE TITLE
What's the current status of this Project ?

### ISSUE THREAD

**Issue by nicolasmendoza** [bernardopires/django-tenant-schemas#548]
Hi, I would like to know what's the status of this Project and if is going to be a abandonware or exists planing continue developing this project ?. I look very interesting this project but the risk to use this package in Production maybe is high, I see a lot of open questions and "issues" without any answer.
I would like to suggest the project to the "Django jazz band" or try to find "contributions" for keeping this project alive. I would like to know what plans the author of this package.

Thanks

**Comment by nicolasmendoza** [comment]
Maybe a good option is moving this to https://github.com/jazzband

**Comment by xgilest** [comment]
I don't know what the plans does @bernardopires has, but as for us we have been using them in production for more than 3 years without any significant problem, Migrations are slow, but we've worked on improving it and will commit and pr some improvement in the following months.
In general, it's an alive project wich solves the multitenancy project in a very elegant, easy way.

**Comment by nicolasmendoza** [comment]
Thanks for your comment and experience. I was a little worried about using this application in production how the solution for several customers that are waiting for the upgrade of our app with a multi-tenant support.

**Comment by herlarb** [comment]
@xgilest I am really worried about using it in production because of the potential of very slow migrations. What Improvements have you done if you can share? Also since you've  used in production how are you looking at scaling the Database  as well as replication? Finally have you tried it on Postgresql 10?

**Comment by AGASS007** [comment]
@herlarb using it in prod with 1000 schemas. To get around slow migrations, the key is to work making sure you make zero down time releases. Once you've got used to doing that, whether the migrations run for 2 minutes or 2 days won't matter.

**Comment by herlarb** [comment]
@AGASS007 What about scaling? Sharding? and Postgres 10 support

**Comment by nicolasmendoza** [comment]
thanks, @AGASS007 good amount of schemas. Now I'm more comfortable with the possibility to implement this package in our production app.

**Comment by AGASS007** [comment]
From what I've gathered — and I've looked, I've never encountered someone complaining about reaching the upper bound of a number of schemas, which I would place above the tens of thousands. The only reported issue is with pg_dump running exponentially longer, but can be mitigated by using it schema by schema. (see [this](http://www.postgresql-archive.org/pg-dump-and-thousands-of-schemas-td5709766.html) for instance).

Don't know sh*t about sharding, so can't help here.

For postgres 10, I haven't tried it, but looking at the [backward incompatible changes](https://wiki.postgresql.org/wiki/New_in_postgres_10#Backwards-Incompatible_Changes), I don't see anything that would compromise this lib. Running the tests on postgres 10 should give you some certainty.

**Comment by herlarb** [comment]
@AGASS007  Thanks for this. Now I can comfortably use this library now.

**Comment by sguermond** [comment]
[django-tenants](https://github.com/tomturner/django-tenants/) is a currently-maintained port of this project.

**Comment by nicolasmendoza** [comment]
@sguermond thanks for the information, I see is maybe a little more "active" but is good know that their package is really a port of this package. Would be nice that all people invert the effort in one package.
What's your experience with Django-tenants and do you know why maintain a port or what's the differences? (I was testing also this package but generally, require Python3 and the last version o Django.

thanks
