### ISSUE TITLE
How to prevent tenants superusers from seeing other tenants in admin?

### ISSUE THREAD

**Issue by hemulin** [bernardopires/django-tenant-schemas#554]
Hi Y'all,

Just started integrating dts into an existing project.

I wish to have a _public_ scheme superuser that can see all the tenants models while other tenants superusers would not be able to access other tenants data.

I have an `organization` app that holds a `Client` model which is also the tenant model.
```
# organization.models.py

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from tenant_schemas.models import TenantMixin

@python_2_unicode_compatible
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until =  models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)
    logo = models.ImageField(upload_to='logos/', null=True)
    auto_create_schema = True

    def __str__(self):
        return self.name
```

The `admin.py` currently is just
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import admin
from organization.models import Client

admin.site.register(Client)
```

When I put `'organization'` in the `SHARED_APPS` section, every tenant can see the other tenants
When I put `'organization'` in the `TENANT_APPS` section, I get the following error running `migrate_schemas`:
```
TypeError: argument of type 'TenantQueryset' is not iterable
```

Is there a standard way to achieve this `super-superuser` access to tenants without letting others tenant superusers to see others?

Cheers

**Comment by kingbuzzman** [comment]
https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_queryset

something like:

```
@admin.register(Client)
class ClientAdmin(admin.ModelAdmin):
    def get_queryset(self):
        return super(ClientAdmin, self).get_queryset().filter(id__in=[connection.get_tenant()])
```

**Comment by hemulin** [comment]
Cool, I get the idea.
Thanks for the link and the snippet :+1: .

**Comment by saileshkush95** [comment]
@hemulin can you share how you solve this, this is not working
