### ISSUE TITLE
Error 'relation "django_session" does not exist' in public tenant, BUT in incognito mode it works OK

### ISSUE THREAD

**Issue by saduqz** [bernardopires/django-tenant-schemas#573]

**Comment by saduqz** [comment]
My tenants work OK, `something.localhost:8000` but my public tenant `localhost:8000` give me that error `relation "django_session" does not exist`. I have 3 laptops and just happened on two of them.

If I go to the incognito mode it works.

**Comment by gnalbandian** [comment]
+1, same behavior. In incognito works.

I do not have dango_sessions in SHARED_APPS, only in TENANT_APPS.

Shall I install it on both? I don't want an authenticated user from one tenant to be logged in other tenants without doing proper login procedure in corresponding tenant site
