### ISSUE TITLE
How to populate schemes after creating the tenants

### ISSUE THREAD

**Issue by marimuthuinchennai** [bernardopires/django-tenant-schemas#574]
Hi,

I need to redirect and populate after successful login for the user to be directed their own tenant. I seen one of the post for this question,, you were deleted that blog,, please provide what to do next to redirection and populate the particular tenant.

**Comment by rajeshyogeshwar** [comment]
Can you be please more elaborate? Because the understanding is that the successful for the user is against his/her tenant. If that is the case, then on successful login you can simply redirect the user from your login view itself. From there on, you can choose the mechanism to populate.

**Comment by marimuthuinchennai** [comment]
> Can you be please more elaborate? Because the understanding is that the successful for the user is against his/her tenant. If that is the case, then on successful login you can simply redirect the user from your login view itself. From there on, you can choose the mechanism to populate.

Ya thanks for your reply I done this
