### ISSUE TITLE
Example app does not successfully set tenant

### ISSUE THREAD

**Issue by rkotcherr** [bernardopires/django-tenant-schemas#580]
I am unable to get the sample app to work.

### What I did
I downloaded the django-tenant-schemas repository, created a virtualenv in the `/examples/tenant_tutorial` directory with `-p python3` and the following requirements.txt:

```
Django==2.1.3
django-tenant-schemas==1.9.0
psycopg2==2.7.6.1
psycopg2-binary==2.7.6
pytz==2018.7
```
I then went to `tenant_tutorial/settings.py` and set DATABASES.default to my local postgresql endpoint and database name.

I was able to successfully run `python manage.py migrate_schemas --shared` as described in the documentation, and the following tables were created:

<img width="190" alt="screen shot 2018-11-12 at 7 22 55 pm" src="https://user-images.githubusercontent.com/37677850/48367250-681a8080-e6b0-11e8-8525-e6126cb96dcc.png">

I then went to the `customers_client` table and created the following clients:

<img width="510" alt="screen shot 2018-11-12 at 7 24 05 pm" src="https://user-images.githubusercontent.com/37677850/48367331-9f892d00-e6b0-11e8-88b2-5825ab61e0fc.png">

I then ran `./manage.py runserver` and was able to visit the webapp successfully.

### The Problem

I am never able to switch tenants. I always see "Current Tenant: None".

One thing I noticed is that I cannot see any print statements that I put in the middleware. I don't know a whole lot about Django yet, so I thought maybe this would be more obvious to somebody else.

I thought it would be appropriate to post here in case there's an update that needs to be made to the example. But most likely it's something I'm not doing quite right, but I'm out of ideas for the moment.

**Comment by rkotcherr** [comment]
Just wanted to write to clarify for anybody else who runs across this issue. My problem was that, although I read the docs, I had just manually entered customers into the database. If you're running across the issue I describe above, be sure to add clients as described. ☹️

**Comment by Regretss** [comment]
Are there any successful cases

**Comment by Regretss** [comment]
How do you add tenant？

**Comment by rkotcherr** [comment]
@Regretss You have to create it via the shell. Create a public schema, and then save it. There's an on-save hook that'll create the schema for you. Please read the "Getting started" part of the docs. Everything is described there.

**Comment by Regretss** [comment]
@rkotcherr Thank you for solving my problem
