### ISSUE TITLE
How to create dynamic models and migrate into particular schema

### ISSUE THREAD

**Issue by marimuthuinchennai** [bernardopires/django-tenant-schemas#611]
model = type(name, (models.Model,), attrs)

the above is my dynamic model

i am trying this command to execute to create table 

call_command('loaddata','model',schema_name=SchemaName,verbosity=0,)

it seems this error for me how to resolve, is it correct way?

**Comment by jeroenbrouwer** [comment]
Use `schema_context`, `tenant_context` or manually set the connection to the right schema. See: https://django-tenant-schemas.readthedocs.io/en/latest/use.html#utils

**Comment by marimuthuinchennai** [comment]
> Use `schema_context`, `tenant_context` or manually set the connection to the right schema. See: https://django-tenant-schemas.readthedocs.io/en/latest/use.html#utils

thanks for your reply 

Instaed of using tenant command i had used this command below thanks for your reply


  siteName = type(siteName, (models.Model,), attrs)
                        with connection.schema_editor() as schema_editor:
                                schema_editor.create_model(ModelName)
