### ISSUE TITLE
cannot pass schema with `showmigrations` command

### ISSUE THREAD

**Issue by khixer** [bernardopires/django-tenant-schemas#620]
I'm unable to view `showmigrations` status while passing schema flag.

input:
  - python manage.py showmigrations --schema=foo
expected output:
  - It should show migration statuses with specified schema context.

**Comment by arneec** [comment]
when you are using ```--schema``` flag you should use ```tenant_command```. for that you can do like``` python manage.py tenant_command showmigrations --schema=foo```
