### ISSUE TITLE
Why is python3 manage.py migrate_schemas not applying migrations?

### ISSUE THREAD

**Issue by mhunchojack** [bernardopires/django-tenant-schemas#627]
![image](https://user-images.githubusercontent.com/57615045/75248233-cc0b7e80-57f9-11ea-8daa-6adfae10cca7.png)

**Comment by adnathanail** [comment]
Is `"crisis_pub"` in your `INSTALLED_APPS` in `settings.py`?

**Comment by mhunchojack** [comment]
Yes it is.

**Comment by mhunchojack** [comment]
I started the project again this time, and this time there were no errors.

**Comment by mhunchojack** [comment]
Though the documentation helped a lot.
