### ISSUE TITLE
PUBLIC_SCHEMA_URLCONF

### ISSUE THREAD

**Issue by kissgyorgy** [bernardopires/django-tenant-schemas#70]
I was thinking about this for quite some time, but now  in connection with #43 I could finally draft this idea:
Get rid of PUBLIC_SCHEMA_URLCONF setting, and in the documentation, suggest a solution with a different wsgi_app for the public website which point to a different settings.py (settings_public).

``` python
# wsgi_main_website.py
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings_public")

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

This would need to set up a new wsgi instance, but I don't think that's a problem and this would have the following benefits:
- We can remove `ContentType.objects.clear_cache()` from the middleware, because this case, every schema would have the same app in contenttypes in the same place.
  This causes +1 DB Query in _every_ request, but if the cache is never cleared, Django (contenntypes) can nicely build up a cache for the objects I think.
  I can't come up with a solution where PUBLIC_SCHEMA_URLCONF is in use and it's not needed to modify Django core to get rid of this behavior.
- as @bcarneiro put the question in #43 :  
  "What does your code do when I have `auth` and `admin` both on public and on tenant?"
  Does the user want shared apps referenced in public? Does he want `public` schema for the public website only and tenant apps without referencing public?
  It would be more clear what it means putting an app into both of the SHARED_APPS and TENANT_APPS; the user made a mistake :) or what would be even better [I described in #43](https://github.com/bcarneiro/django-tenant-schemas/issues/43#issuecomment-24862535), to have a SHARED_MODELS setting.
- Sometimes for the public website you want to have a CMS ex. http://www.django-cms.org, which want to take some control of the url routing because of dynamic pages, etc, and it would be very hard to integrate with this app.

I will do it myself for sure, because I think overall this is the right way to do it but would be nice to get some comments on this one, and I think others could benefit from this also.

**Comment by juliocesar-io** [comment]
Hi guys, I know is been a lot time since this discussion but I din't found much in the docs. If I setup a separate WSGI settings, how do I declare database settings?  Should I use the default postgresql backend for django? How do I manage the migrations? And in this separate settings the `django-tenant-shemas `app would exist ?
