### ISSUE TITLE
What is the easiest way to build a multitenant service with CMS?

### ISSUE THREAD

**Issue by Draqun** [bernardopires/django-tenant-schemas#703]
Hi. I am interested in using the django-tenant-schemas package in a fairly simple project. I want to have a simple application where I have a few static sub-pages (About, Homepage, etc.), a sub-page that allows each user to create their own tenant, and a sub-page that is a blog where each user of the system can write. What will be the best stack for this task?

The second question refers to the documentation -> https://github.com/bernardopires/django-tenant-schemas/blob/master/docs/use.rst#creating-a-tenant
You provide the code, but do not indicate where to put this code. I would assume it would be a migration file, but I have not been able to do a migration where I put the code. Any documentation update I could ask for?

Best regards.
Draqun

**Comment by mast3rbow** [comment]
You need to create a tenant model, which is what that code is doing.

Co-founder
Bryton Wishart
+61427594365
***@***.***



________________________________
From: Damian Giebas ***@***.***>
Sent: Sunday, October 27, 2024 6:26:22 AM
To: bernardopires/django-tenant-schemas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bernardopires/django-tenant-schemas] What is the easiest way to build a multitenant service with CMS? (Issue #703)


Hi. I am interested in using the django-tenant-schemas package in a fairly simple project. I want to have a simple application where I have a few static sub-pages (About, Homepage, etc.), a sub-page that allows each user to create their own tenant, and a sub-page that is a blog where each user of the system can write. What will be the best stack for this task?

The second question refers to the documentation -> https://github.com/bernardopires/django-tenant-schemas/blob/master/docs/use.rst#creating-a-tenant
You provide the code, but do not indicate where to put this code. I would assume it would be a migration file, but I have not been able to do a migration where I put the code. Any documentation update I could ask for?

Best regards.
Draqun

**Comment by Draqun** [comment]
Thank you for the response. Can you answer two more questions?

1. How to rollback last migration? I use the following command `poetry run python src/manage.py migrate_schemas --executor=parallel --shared common zero` but it reverts all migrations.
2. Generally in the documentation you advise against using the migrate command, is migrate_schemas able to do all that the migrate command can do?

**Comment by mast3rbow** [comment]
So, it uses the same approach as Django migrations. By putting in Zero you are rolling back to pretty much no models in your DB. 

You migrations will be numbered rollback to the suitable ones. you want to use migrate_schemas if your using this package, as it will ensure it does it across all your schemas. Ideally don't use migrate if you are using this as it only does the public schema I believe.

**Comment by Draqun** [comment]
Since I didn't know what to expect from the behavior of “django.contrib.auth” when I put together the project according to the documentation I checked myself what and how and I have the following questions.

1. Is it possible to create a user within the tenant application so that when logged in, they can access resources with SHARED_APPS that require a login?
2. Is it possible to use “django.contrib.auth” only in SHARED_APPS and access tenant resources that require login?

Currently, I don't see how to manage shared resources when the user is in the tenant schema, and vice versa manage tenant resources when the user is in the public schema. However, it is possible that I am wrong and there is such a possibility, in which case I would ask for an example and an update to the documentation.

**Comment by Draqun** [comment]
Hi I think the issue can be closed. I tried few ideas and some of them works. 

Best regards.
